### ISSUE TITLE
Set up company code at website or store view level

### ISSUE THREAD

**Issue by ipekerti** [classyllama/ClassyLlama_AvaTax#1]
We have a single AvaTax account w/ two companies with different nexus configurations.  We have installed the extension successfully on a single instance of Magento 2, but seems to only be able to define company code at the Global level, not at the website or store view level.

In our case, each of the two companies will have its own separate website/storeview.

Any way to do this?  Or a work around perhaps?

Thanks!

**Comment by erikhansen** [comment]
Configuring company code at anything other than the global level is currently not supported, but we will certainly consider adding this functionality for future releases of this extension.

**Comment by erikhansen** [comment]
Release 0.1.9 adds this functionality, so closing this issue: https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/0.1.9
