### ISSUE TITLE
Issues in placing order for Utha

### ISSUE THREAD

**Issue by deepikajaniyani** [classyllama/ClassyLlama_AvaTax#106]
### Preconditions
1.  Magento EE 2.1.9 and AvaTax 1.0.2

### Steps to reproduce
1.  Whenever customer tries to place an order with shipping address of UTHA, then an error is thrown stating "An error occurred on the server. Please try to place the order again." but the order gets submitted in Magento 
2. Since customer feels that order is not submitted, he keeps on clicking the Submit order button due to which duplicate orders get submitted. 

### Expected result
1. Customer should be able to see order success page.

### Actual result
Customer is returned with error "An error occurred on the server. Please try to place the order again."

When we debugged this further we observed that, 
1. For a cart item two types of taxes are returned, a. Product b. Shipping
2. For orders that belong to Utha, Avatax is not calculating the tax for shipping amount, this may be due to some judicial rules for Utha state, we found one article which states the same, refer link (https://blog.taxjar.com/is-shipping-taxable-in-utah/).
3. The tax is already saved for Product level using Avatax calculations.
4. Since the tax is not returned for Utha state for shipping amount from Avatax, the code fall backs to Default Magento code for calculating the tax, and in that process, it tries to re save the tax for Product also due to which a DB level error comes for integrity constraints and duplicate orders get generated.

**Comment by rsisco** [comment]
@deepikajaniyani - According to that link, if shipping is listed separately (as it is natively in Magento 2), then it is not going to be taxed. Do you get an error in the tax response from Avalara? You can use the information in the [troubleshooting section](https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#troubleshooting) of the AvaTax extension documentation to get details on how to view the request/response. If there is no error, then Magento should not try to fallback on its own tax codes. Returning no sales tax in the response is not the same as an error.

Are you able to reproduce the issue in a vanilla Magento 2 environment (plain Magento 2 install with no extensions or customizations)?

**Comment by deepikajaniyani** [comment]
Hi @rsisco ,
Thanks for the updates, we have enabled the trouble shooting section and debugged further. 
We are not receiving any error from Avalara. 
The only difference we received in response was the data for `TaxCalculated` item in `shipping` tax-line, details below 

**Response for Utha:** 
1 => 
      AvaTax\TaxLine::__set_state(array(
         'No' => 'shipping',
         'TaxCode' => 'FR020100',
         'Taxability' => true,
         'BoundaryLevel' => 'Zip5',
         'Exemption' => '0',
         'Discount' => '0',
         'Taxable' => '0',
         'Rate' => '0.088750',
         'Tax' => '0',
         'ExemptCertId' => 0,
         'TaxDetails' => 
        stdClass::__set_state(array(
        )),
         **'TaxCalculated' => '0',**
         'ReportingDate' => '2018-02-06',
         'AccountingMethod' => 'Accrual',
         'TaxIncluded' => false,
         'TaxDate' => '2018-02-06',

**Response for Other states:**
1 => 
      AvaTax\TaxLine::__set_state(array(
         'No' => 'shipping',
         'TaxCode' => 'FR020100',
         'Taxability' => true,
         'BoundaryLevel' => 'Address',
         'Exemption' => '0',
         'Discount' => '0',
         'Taxable' => '7.98',
         'Rate' => '0.065000',
         'Tax' => '0.52',
         'ExemptCertId' => 0,
         'TaxDetails' => 
        stdClass::__set_state(array(
        )),
         **'TaxCalculated' => '0.52',**
         'ReportingDate' => '2018-02-06',
         'AccountingMethod' => 'Accrual',
         'TaxIncluded' => false,
         'TaxDate' => '2018-02-06',

Also we are using Magento EE 2.1.9 and AvaTax 1.0.2. We have not checked this issue in vanilla Magento instance yet.

**Comment by rsisco** [comment]
@deepikajaniyani - It doesn't look like this is an issue with the AvaTax extension; as far as I can tell, the shipping charges for addresses in Utah should _not_ have sales tax calculated for them.
I would suggest working with [Avalara support](https://www.avalara.com/support/) to determine whether or not your sales tax is working properly and they will direct you back to support for the extension if that is deemed necessary.

Closing this issue for now.

**Comment by deepikajaniyani** [comment]
Hi @rsisco ,

As you can see from the logs, Tax for Utha is not calculated, TaxCalculated is 0 in response for Utha, the one response that has the TaxCalculated as 0.52 is for other state.

I had shared 2 response to show the difference between the two for TaxCalcluated field in shipping response.

**Comment by rsisco** [comment]
@deepikajaniyani - Is tax not calculating at all for Utah, or just not for shipping in Utah? Tax should not be calculated for shipping in all states. Only some states charge sales tax on shipping charges, and Utah is not one of them. My suggestion is to contact Avalara support to make sure that your account is calculating sales tax correctly.

**Comment by deepikajaniyani** [comment]
@rsisco ,
Please find updates below,

[Rsisco] Is tax not calculating at all for Utah, or just not for shipping in Utah? 
[Deepika] Tax is not calculating only for Shipping in Utah, tax is returned for other order total. 

[Rsisco] Tax should not be calculated for shipping in all states. Only some states charge sales tax on shipping charges, and Utah is not one of them. 
[Deepika] As per our experience with the tax, tax is getting calculated for shipping in all states and it returns 0 only for Utah, which is correct. We have not observed this scenario for other states. 

[Rsisco] My suggestion is to contact Avalara support to make sure that your account is calculating sales tax correctly.
[Deepika] Initially we had did the same, we have shared this ticket details also with Avalara team and waiting for their inputs.
