### ISSUE TITLE
Saving Address From Address Book on User Dashboard

### ISSUE THREAD

**Issue by inspiredchu** [classyllama/ClassyLlama_AvaTax#11]
When the user (who hasn't saved an address yet) goes to the My Account page and then clicks on "Address Book" and then tries to save the address he receives this error message:

%fieldName is a required field.

The xhr states a '400 Bad Request' status and has the following response:
{"message":"%fieldName is a required field.","parameters":{"fieldName":"storeId"},"trace":"#0 \/var\/www\/magento\/vendor\/magento\/framework\/Webapi\/ServiceInputProcessor.php(111): Magento\\Framework\\Webapi\\ServiceInputProcessor->processInputError(Array)\n#1 \/var\/www\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(262): Magento\\Framework\\Webapi\\ServiceInputProcessor->process('ClassyLlama\\\\Ava...', 'saveValidAddres...', Array)\n#2 \/var\/www\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(160): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#3 \/var\/www\/magento\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(24): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/var\/www\/magento\/vendor\/magento\/framework\/App\/Http.php(115): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 \/var\/www\/magento\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#6 \/var\/www\/magento\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#7 {main}"}

It looks like $storeId is not being passed to the method saveValidAddress($address, $storeId) in ClassyLlama/AvaTax/Model/ValidAddressManagement.php.

I'll take a deeper look into this later and let you guys know what I found. Please let me know if you are able to recreate the issue. We are running Magento 2.0.4.

**Comment by erikhansen** [comment]
@inspiredchu This was fixed in 0.1.4. Please download and install the latest version of the extension (0.2.0) and your problem should be resolved: https://github.com/classyllama/ClassyLlama_AvaTax/releases
