### ISSUE TITLE
Duplicate Address Entities Created

### ISSUE THREAD

**Issue by rsisco** [classyllama/ClassyLlama_AvaTax#115]
When AvaTax address validation is enabled, if a customer with no saved addresses checks out using the same address for billing and shipping, the result will be the creation of two separate (but identical) address entries for the customer.

### Preconditions
1. Magento 2.x
2. AvaTax extension is installed with address validation enabled

### Steps to reproduce
1. Create a new customer account, but do not add any addresses to the account
2. Add item(s) to cart and proceed to checkout
3. Provide a shipping address and allow Magento to use the same address for billing
4. Place order

### Expected result
1. A single address entry will be created for the customer

### Actual result
1. The provided address is saved twice, as two separate address entities; once as the default shipping address and once as the default billing address.
![img](http://take.ms/ogPIQ)
2. This results in the availability of two identical address choices when the customer checks out with their next order.
![img](http://take.ms/dgeGF)

**Comment by VolodymyrEl** [comment]
Any ideas how to fix this bug? Maybe problem here [https://github.com/classyllama/ClassyLlama_AvaTax/blob/develop/Plugin/Checkout/Model/ShippingInformationManagement.php].

**Comment by rsisco** [comment]
@VolodymyrEl - I have not had the opportunity to start digging into this yet. If you have the ability to create a solution, feel free to submit a PR back to the repo and we will review and include your changes in the codebase as appropriate.

**Comment by parththummar** [comment]
Any update on this? we are also facing the same issue.

**Comment by rsisco** [comment]
@parththummar - The issue is being investigated, but we do not yet have a fix.

**Comment by rsisco** [comment]
This issue has been addressed in release #[1.4.9](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.4.9). Closing issue.
