### ISSUE TITLE
Region "12" Not Found Error

### ISSUE THREAD

**Issue by matthew-valenti** [classyllama/ClassyLlama_AvaTax#117]
Error in checkout when calculating tax. Error in avatax.log is:
['2018-03-27 20:14:07'] 'avatax'.'ERROR': 'Region "12" was not found.'  array (
  'store_id' => '1',
)

### Preconditions
1. Magento Enterprise version 2.2.2 (with B2B features installed/enabled).
2. Hosted on Magento Cloud.
3. PHP version 7.x, DB version
4. /composer.json: "avalara/avatax": "15.5.2.0", "classyllama/module-avatax": "^1.3"

### Steps to reproduce
1. Add item to cart and checkout.
2. On checkout, choose a shipping method and click "Next" button. Error displayed and logged in avatax.log.

### Expected result
1. Calculated tax to display on checkout page.

### Actual result
1. The following screencast (with audio) details our install/setup/result: _link removed_
2. Ignore my comment about hard coded Region ID in SetupUtil.php -- that's simply a test case.
3. The error message looks to be coming from here:
File: /vendor/classyllama/module-avatax/Framework/Interaction/Address.php
Function: getRegionCodeById
Line 485: 'Region "%1" was not found.'

**Comment by rsisco** [comment]
@matthew-valenti - Thank you for the detailed screencast. To address your concern over the hardcoded region you found, that is in the integration tests code, which isn't part of what is executed with the code. Would you mind providing me a database export of just your _directory_country_region_ and _directory_country_region_name_ tables?

**Comment by rsisco** [comment]
@matthew-valenti Actually, I don't need your DB dumps. I have confirmed that I can reproduce this locally through the following actions:

- Set my store's origin address to one in California (_STORES > Settings > Configuration > SALES  > Shipping Settings > Origin_)
- Change the region ID for California in the _directory_country_region_ and _directory_country_region_name_ database tables
- Attempt to checkout as a customer

This results from the fact that Magento stores the region defined for the shipping origin address in the _core_config_data_ table with a path of _shipping_origin_region_id_ and it does not get updated if the region ID changes in the DB tables for regions.

The easiest fix is to navigate to the origin path definition in the config, set the correct region/state, save the config, and clear the cache.

Can you confirm that this is your experience as well?

**Comment by rsisco** [comment]
Note that this will also affect AvaTax's application of tax if specific regions have been defined as taxable within Magento prior to their IDs changing in the DB.

**Comment by rsisco** [comment]
@matthew-valenti - I updated my previous comment to you with a second scenario that also be the case for your instance.

**Comment by matthew-valenti** [comment]
Thank you! Issue confirmed resolved by simply updating Magento origin configuration. Stores > Configuration > Sales > Shipping Settings > Origin. This is what our out-of-the-box origin config looked like: https://www.screencast.com/t/PalyHKlm.  Interestingly, I saw 12 appear on the screen briefly when rendering the form field. If region CA with id 12 existed in our database I'd expect to see California as the default setting here. Note that we do not use the Magento origin, we are using ShipperHQ multi-origin feature. That is why we left Magento origin config as the default.

**Comment by navarr** [comment]
Hi @rsisco,

I recently experienced this error in a Magento Cloud setup where we had not configured the shipping origin address.

If that origin is required, I would expect to see an error message if it is incorrect (or at least the error message about the region id to point to what address its processing)

**Comment by rsisco** [comment]
@navarr - We may consider adding some sort of validation in the future. For now, the [configuration steps](https://github.com/classyllama/ClassyLlama_AvaTax/blob/develop/docs/getting-started.md#configuration) in the documentation specifically mention the need for configuring the origin address.
