### ISSUE TITLE
Tax Amount Doesn't Display With Digital Products Checkout

### ISSUE THREAD

**Issue by sb-rustam** [classyllama/ClassyLlama_AvaTax#121]
Taxes do not display on the checkout page when buying a single or multiple digital products. However they are being collected and charged correctly once the order will be placed. Taxes display just fine for normal goods (physical products) in our case. Digital products (ebooks) have been assigned tax code “DB020000” which is the same tax code we’ve been using for several years in Magento 1. 
 
The following address was used as customer's default address:
2230 NJ-10
Morris Plains, New Jersey, 07950
United States
 
This reference links denotes that taxes do calculate in NJ for digital products. https://www1.avalara.com/us/en/learn/whitepapers/identification-taxability-of-digital-products.html
 
### Preconditions

1. Tested in Magento Commerce Edition 2.2.3, vanilla Magento instance with a sample data was installed through Composer,  default Luma theme was used. No any customizations other than  installed AvaTax module.
2. The AvaTax module info: version 1.4.1, installed through Composer.

### Steps to reproduce

1. This issue happenes only if customer has a virtual product on the basket and no phisycal products.
2. Customer registered account from frontend of the website.
3. Customer has 2 different addresses, both addresses within nexus states. For example:
No sales tax for digital goods:
1935 Brookdale Rd
Suite# 139
Naperville, Illinois, 60560
United States
T: 6309613900

Sales tax will be charged for digital goods:
Sourcebooks NJ Office
2230 NJ-10
Morris Plains, New Jersey, 07950
United States
T: 6309613900 
Default billing and shipping address

The NJ address should be marked as default billing and shipping address.

4. Sample product with SKU “240-LV05” was used to test this issue, it is a downloadable product.
5. Avalara sandbox account was used, setup a new product tax class for downloadable products in Magento2: 
eBook DB020000
6. Customer adds the product with SKU “240-LV05" on the basket, from storefront. Once product was added, then customer clicks to the “Proceed Checkout” button from the mini cart popup window.
7. After that customer should be redirected to the one page checkout page, since the basket contains a virtual product only.
8. But the sales tax amount doesn't display at the checkout. Please find the attached screenshot for more details. However it will be charged during the order placement process, once customer clicks the "Place Order" button.
9. Please note that the tax amount will be displayed correctly on the following cases (on the final checkout page):
- if customer will change they billing address from dropdown box
- if customer applies promotion or gift card codes and page will be reloaded
But the tax amount doesn't display when customer's address was set to NJ address by default and non of the above actions will be performed at the final checkout page.

### Expected result

1. The sales tax amount should be displayed on the final checkout step.

### Actual result

1. Taxes do not display on the final checkout page. However they are being collected and charged correctly once the order will be placed.

![screenshot](https://user-images.githubusercontent.com/13275393/38898311-3b3e45a6-425a-11e8-8c1b-d5457ee13192.png)

**Comment by rsisco** [comment]
@sb-rustam I have confirmed that I can reproduce this issue. Please watch this issue for updates.

**Comment by rsisco** [comment]
This issue has been addressed in release #[1.4.9](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.4.9). Closing issue.
