### ISSUE TITLE
Custom first checkout step and review & payments are combine when ava tax is enabled.

### ISSUE THREAD

**Issue by natebatty** [classyllama/ClassyLlama_AvaTax#123]
### Steps to reproduce

1. Create a custom first step for checkout
2. Add only Digital products to your cart (No Shipping Need)
3. Checkout - Custom First Step and Review & Payments are combine.

### Expected result

1. If you disable ava tax, the two steps correctly display as separate steps.

### Actual result

1. Custom First Step and Review & Payments are combined as one with both steps being highlighted

**Comment by erikhansen** [comment]
@natebatty Unfortunately we don't support highly customized checkout flows, so we're not able to address this issue.
