### ISSUE TITLE
Add new line item to Avatax Call

### ISSUE THREAD

**Issue by deepikajaniyani** [classyllama/ClassyLlama_AvaTax#126]
This is not an issue, but basically a customization.

We have a module, in which additional fee is added to the Order based on some conditions. This additional fee should be taxed. This works well with the default Magento tax calculations, but not works if we are using Avatax.

Is there any way we can add this new line item to the tax calculation calls?

**Comment by deepikajaniyani** [comment]
We also found a function called "processExtraTaxables" that can be used for making this fee taxable, but how can we link the two?

**Comment by hmartDev** [comment]
Hi @deepikajaniyani. We have the same situation that customized fee is not shown in AvaTax transactions. Did you find any solution for it? Any feedback will be appreciated!

**Comment by deepikajaniyani** [comment]
We extended function getGetTaxRequestForSalesObject of class ClassyLlama\AvaTax\Framework\Interaction\Tax and added the new line item to it. 

The below code goes after all the line items (lines[]) gets populated. 

        $countLine = count($lines);
        if ($order->getFee() > 0) {
            $line = $this->getEcoFeeLineItem($object, $countLine, $credit);
            if ($line) {
                $lines[] = $line;
            }
        };

Once the above code is added, you can add the below function anywhere in the file. 

	public function getEcoFeeLineItem($data, $countLines, $credit)
    {
        $ecoFee = $data->getFee();

        if ($credit) {
            $ecoFee *= -1;
        }

        $data = [
            'No' => $countLines+1,
            'ItemCode' => 'EHF',
            'TaxCode' => 'EHF',
            'Description' => 'Eco Fee For BC',
            'Qty' => 1,
            'Amount' => $ecoFee,
            'Discounted' => false,
        ];

        try {
            $data = $this->metaDataObject->validateData($data);
        } catch (\ClassyLlama\AvaTax\Framework\Interaction\MetaData\ValidationException $e) {
            $this->avaTaxLogger->error('Error validating line: ' . $e->getMessage(), [
                'data' => var_export($data, true)
            ]);
        }
        /** @var $line \AvaTax\Line */
        $line = $this->lineFactory->create();

        $this->populateLine($data, $line);
        return $line;
    }
