### ISSUE TITLE
Address validation error not being handled properly in Magento 2.2.x

### ISSUE THREAD

**Issue by ipekerti** [classyllama/ClassyLlama_AvaTax#128]
### Preconditions
1. Magento Community 2.2.3
2. Avatax extension 1.4.0
3. PHP 7

### Steps to reproduce
1. Sign in as registered user
2. Add item to cart,  proceed to checkout
3. On the Shipping Address checkout page, add a new shipping address, tick the the "Save to Address Book" checkbox.  Use an address that Avatax is unable to validate, but customers may insist is the correct shipping address.  Here are a couple of sample addresses:
AT&T
207/209 F ST.
SOUTH BOSTON MA 02127

NASA LOGISTICS
BLDG 839
VANDENBERG AFB CA 93437

3. Click the NEXT button to proceed to Payment checkout page

### Expected result
1. Customers should be properly warned that the address cannot be validated, and may proceed with the checkout process should they insist that the shipping address is correct.

### Actual result
1. There are no log entries generated at all.
2. A **blank ERROR** alert box is displayed with no explanation.
3. The customer is unable to continue the checkout process, focus returned to Shipping Address Checkout page.

Regards,
Immanuel Pekerti

![avatax-validation-error-setting](https://user-images.githubusercontent.com/17164724/41755767-9699fb80-759e-11e8-9757-a13dd7d5bf95.PNG)

![checkout-error](https://user-images.githubusercontent.com/17164724/41755773-9d3eb804-759e-11e8-8882-0160b4502dbc.png)

**Comment by ipekerti** [comment]
This behavior also applies to Guest checkouts as well.

**Comment by rsisco** [comment]
@ipekerti - Can you try [increasing the logging level](https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#troubleshooting) for AvaTax and ensure that no errors are being logged? I am unable to reproduce this issue:
![img](http://take.ms/QkkXa)

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com
