### ISSUE TITLE
[Data Migration] Does information from op_avatax_queue  and op_avatax_log need to be migrated?

### ISSUE THREAD

**Issue by roma-glushko** [classyllama/ClassyLlama_AvaTax#131]
I'm wondering if _op_avatax_queue_ and _op_avatax_log_ tables should be migrated from Magento 1 to Magento 2. I'm gonna use Avatax on Magento 2 as well, so it's important to know how it can impact the system if that tables are not migrated. Would there some kind of inconsistency?

In op_avatax_queue table has both records with statuses Complete and Unbalanced and in op_avatax_log table has records with level Success and Error

**Comment by rsisco** [comment]
It is not necessary to migrate the AvaTax log data from M1 to M2, as it is only used for troubleshooting, investigating tax calculation discrepancies, etc. Make sure the M1 AvaTax queue is processed and free of pending entries before switching to M2 and then the queue data doesn’t need to be migrated either. All tax collection records should be available in Avalara’s AvaTax dashboard.
