### ISSUE TITLE
Module not compatible with Magento 2.3

### ISSUE THREAD

**Issue by dverkade** [classyllama/ClassyLlama_AvaTax#137]
With the upcoming release of Magento this module should be compatible with version 2.3.

### Preconditions
1. Magento 2.3.0 Alpha

### Steps to reproduce
1. Install the Avatax module with composer.

### Expected result
1. Module should be installed

### Actual result
1. Module can not be installed due to version constraints, see screenshot:
![image](https://user-images.githubusercontent.com/1058480/42185398-be32b300-7e16-11e8-8569-b589c0029070.png)

**Comment by rsisco** [comment]
@dverkade - We haven't yet tested the extension's compatibility with 2.3 so we haven't updated the composer dependencies to allow its installation yet.

**Comment by dverkade** [comment]
@rsisco check the PR's where I have submitted fixes to make the module compatible with Magento 2.3.

**Comment by michaeljdietz** [comment]
Any word when we can expect a version compatible with 2.3 now that 2.3.0 has been officially released?

**Comment by lyoshigw** [comment]
Has there been any updates? We want to update to Magento 2 v2.3 on Enterprise, but are concerned about its compatibility with Avatax

**Comment by vadim4err** [comment]
also we have the same issue. waiting for ClassyLlama response

**Comment by rsisco** [comment]
We are in the final steps of testing and revising the extension for 2.3 compatibility and expect to push a new release in the next few days.

**Comment by rsisco** [comment]
Code revisions addressing this issue have been merged into the develop branch and will be included in the next release.

**Comment by dverkade** [comment]
@rsisco what I find weird is that my PR is not merged, instead you have decided to copy my changes and commit them again on a different branch. Would be nicer to recognise the work that has already been done voluntarily and give credits for it.

**Comment by rsisco** [comment]
@dverkade - I apologize for not being clear. We needed to modify your work slightly, but will give attribution to you in the changelog when the new version is released. Thank you for your contribution.

**Comment by rsisco** [comment]
This issue has been addressed in release [1.5.0](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.5.0).
