### ISSUE TITLE
"Orders" tab is missing on Customer Edit page

### ISSUE THREAD

**Issue by yrudiuk** [classyllama/ClassyLlama_AvaTax#151]
Hello,

1.4.3 version is breaking tabs on Customer Edit page in admin.

Specifically this file - vendor/classyllama/module-avatax/view/adminhtml/layout/customer_index_edit.xml
Native "Orders" tab is missing.

We are using Magento 2.1.7

Thanks!

**Comment by rsisco** [comment]
This has been addressed in version [1.4.8](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.4.8). Closing issue.
