### ISSUE TITLE
Problem Report: AvaTax Queue Empty w/Errors; Case 15612988 ref:_00D30Psz._5000b1IC5EE:ref

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#154]
Hello Classy Llama Support,
                Please assist with the issue below. It may be an install issue, but upgrading to the latest version of the extension did not resolve the issue.

{*}Account Name:{*} Pearl Unlimited Holdings Inc. 
{*}Account Number(s):{*} 2000003518 
{*}Company Code(s):{*} 967 
{*}AvaTax Environment:{*} PROD 
{*}ERP Version:{*} Magento 2.2.3 Community - AvaTax 1.4.3
{*}AvaTax Integration Version:{*} 
{*}AvaTax Adapter Version:{*} 15.5.1.0 
{*}OS/Browser Version:{*} Chrome 
{*}Repro Frequency{*} 100%

Customer contact info: 

William Voegeli 
(770) 241-4494 
will.voegeli@allycommerce.com 

{*}Description:{*} Hello. I noticed one of our Magento stores has a warning message in the Magento admin site that says, "The AvaTax Queue has 77 document(s) that failed during processing and were not successfully sent to AvaTax. Check the queue." 

However, when I check the queue it says, "Last Processed at Jul 20, 2018 11:55:03 AM - Queue Records Waiting To Be Processed: 0 Notice: Undefined index: entity_type_code in /var/www/htdocs/vendor/classyllama/module-avatax/Ui/Component/Listing/Columns/QueueActions.php on line 70/" 

When I click Process Queue Now it says, "The queue was successfully processed. 0 queued records were processed." 

We have Magento orders dating up to July 21, but I don't see any transactions in our AvaTax Admin Console for the Company in question. 

{*}Steps to Reproduce:{*} Review AvaTax queue
Click Process Queue Now
Review results (Successful, yet nothing happens)

{*}Expected Result:{*} Expects the Queue be processed when he runs it and that the data should show in the admin console after the Job runs. 

{*}Actual Result:{*} Queue processes and transactions do not show in the admin console. Error/warnings persist

{*}Attachments/Documentation:{*} Screenshots

Let us know if you have any questions, concerns, or issues.

Thank you,

Joshua Queen | Product Support Specialist III 
Office:  (206) 826-4900
joshua.queen@avalara.com
Avalara | Making sales tax less taxing

**Comment by rsisco** [comment]
Closing this issue as it was resolved via email and the issue was related to malformed AvaTax tables in the merchant's Magento database.
