### ISSUE TITLE
The extension breaks few functionalities in magento 2 enterprise edition

### ISSUE THREAD

**Issue by rameshpushparaj** [classyllama/ClassyLlama_AvaTax#16]
Recently installed this extension using composer as specified in the official documentation. I am using magento 2 enterprise edition 2.0.4. However after installing the extension few sections like avatax logs and other admin menus were not appearing. New Tax Rule add section is breaking.

However only the admin configuration section works fine. In one page checkout unable to edit the suggested address (that comes after address verification).

The extension works fine in community edition but breaks in Enterprise edition.
![avataxlogsmissing](https://cloud.githubusercontent.com/assets/19649012/15649080/6bada524-268c-11e6-8661-c671ebb71d02.png)
![taxrulebreaks](https://cloud.githubusercontent.com/assets/19649012/15649083/702f3e28-268c-11e6-84e2-44a148790b24.png)
![config-works](https://cloud.githubusercontent.com/assets/19649012/15649085/731b47b2-268c-11e6-8a7a-52702955e597.png)

**Comment by erikhansen** [comment]
@rameshpushparaj I've never seen this issue. I suspect it has something to do with your environment.

1. I presume you flushed all caches? Do those sections show if you disable caching (SYSTEM > Cache Management)?

2. What mode is your site running in (production, default, developer)?

3. If you're running in production mode, did you make sure to run `bin/magento setup:di:compile-multi-tenant`?

**Comment by rameshpushparaj** [comment]
1. I have disabled all the cache management, flush caches still the sections doesn't shows up.

2. Site is running in developer mode.

3. No we are not running in production mode, we were testing this in development environment.  Why does the tax rules section is not working when i enable this module. if i disable the module the new tax rule page is working.

**Comment by erikhansen** [comment]
@rameshpushparaj Can you try to visit the "new tax rule" page and send me whatever error(s) are showing up in your Magento/php/apache/nginx error logs?

**Comment by rameshpushparaj** [comment]
I don't have permission to access the error logs will try to get it from server team. But however in my localhost wamp server when investigated the error log, i got the below one from php_error.log. Will this one help??

31-May-2016 11:34:44 UTC] PHP Notice:  Use of undefined constant BP - assumed 'BP' in D:\wamp64\www\m2testing\vendor\classyllama\module-avatax\registration.php on line 12

**Comment by erikhansen** [comment]
The `BP` constant should be defined when the `app/autoload.php` file is loaded, so I don't know how `vendor\classyllama\module-avatax\registration.php` could be loaded before that constant is defined. Send me the error logs from your server team when you get them.

**Comment by rameshpushparaj** [comment]
Just now found, the module output was disabled in the admin, this was the root cause for the issue. When i enabled it again it works fine.
Anyway thanks for your support. Closing this issue.

**Comment by erikhansen** [comment]
@rameshpushparaj Glad you got it working.
