### ISSUE TITLE
Logging not working after setup:di:compile

### ISSUE THREAD

**Issue by erikhansen** [classyllama/ClassyLlama_AvaTax#17]
# Steps to reproduce

1. Install the AvaTax extension.
2. Compile using: `bin/magento setup:di:compile`
3. Any actions that trigger the AvaTax code will result in this error "$serverData must be an array or object implementing ArrayAccess": ![image001](https://cloud.githubusercontent.com/assets/129031/15680988/43889892-271d-11e6-8a72-918dc4b06b2a.png)

# Overview of issue

This issue is being caused because the `\ClassyLlama\AvaTax\Model\Logger\FileHandler` and `\ClassyLlama\AvaTax\Model\Logger\DbHandler` classes are getting the `\Monolog\Processor\WebProcessor` class via dependency injection. However whenever Magento `\Magento\Framework\ObjectManager\Config\Compiled::getArguments` method is called to get the constructor arguments for the `\Monolog\Processor\WebProcessor` class, since that class doesn't have any arguments specified in `di.xml`, the `WebProcessor` class defaults to getting a single argument which is an instance of `Magento\Framework\ObjectManagerInterface` (see https://github.com/magento/magento2/blob/2.0.6/lib/internal/Magento/Framework/ObjectManager/Config/Compiled.php#L79)

**Comment by erfanimani** [comment]
I came across this issue, and another way to solve it is to create a virtualType with null arguments for the web processor:

    <virtualType name="MyWebProcessor" type="Monolog\Processor\WebProcessor">
        <arguments>
            <argument name="serverData" xsi:type="null"></argument>
            <argument name="extraFields" xsi:type="null"></argument>
        </arguments>
    </virtualType>

**Comment by erikhansen** [comment]
@erfanimani Would you be interested in submitting a PR to resolve this issue?

**Comment by erfanimani** [comment]
My bad @ericthehacker — I came across the same root issue, but not in this specific module :)

(This issue comes up #1 for the search "$serverData must be an array or object implementing ArrayAccess.")

**Comment by erikhansen** [comment]
@erfanimani Ok, no problem.
