### ISSUE TITLE
negative tax and zero grand total if there's a discount

### ISSUE THREAD

**Issue by ebaschiera** [classyllama/ClassyLlama_AvaTax#174]
Hello,
I am having a 0 total order and negative tax amount when I use a 99% discount.
Please note that I have a per-website configuration. On default Avalara is disabled, on a certain website Avalara is enabled and configured.

### Preconditions

1. Magento EE 2.2.5
2. AvaTax module is latest develop version (latest commit: https://github.com/classyllama/ClassyLlama_AvaTax/commit/478ff3da798242699dc471f85f9389546705470e ).

### Steps to reproduce

1. setup a cart price rule of 99% with a coupon code (free shipping is not necessary)
2. place an order with that discount

### Expected result

1. I should get tax > 0 and grand total > 0, as seen at checkout
![1-avalara-checkout](https://user-images.githubusercontent.com/5667462/45611774-e4059d00-ba60-11e8-934a-30caa97f047c.png)

### Actual result

1. The order has a negative tax and a grand total = 0.
![2-avalara-order](https://user-images.githubusercontent.com/5667462/45611785-ebc54180-ba60-11e8-951a-011d1d54e0a3.png)

Thank you!

**Comment by ebaschiera** [comment]
I figured out the problem was in the tax configuration.
I was mislead by the instructions I highlighted in the screenshot. It's not completely true that those settings are ignored. If they are not set correctly, calculation will fail.
![avalara instructions](https://user-images.githubusercontent.com/5667462/46655337-a1406c00-cbab-11e8-833c-f619b4507b43.png)

**Comment by rsisco** [comment]
@ebaschiera - Can you tell me what values you were using for those settings? They _should_ be ignored, but I would like to confirm the behavior myself.

**Comment by ebaschiera** [comment]
Hi @rsisco ,
values I was using are:
Catalog Prices: Including Tax
Shipping Prices: Including Tax
Apply Discount On Prices: Including Tax.

Thank you.
