### ISSUE TITLE
Taxes rounded to two decimal places when using modue

### ISSUE THREAD

**Issue by StephenBadger** [classyllama/ClassyLlama_AvaTax#179]
The issue is that when using the Avatax module, the tax summary in checkout is rounded to two decimal places.

### Preconditions

1. Magento 2.2.3 
2. avalara/avatax 15.5.2
3. PHP 7.0.31

### Steps to reproduce

1. Prepare an order, go to checkout, set shipping to Quebec.
2.  Get tax summary to display (configure in the backend of magento if needed)
3.  Note that QST is shown as 9.98, where it should be 9.975
4. To test Magento Core taxes, to contrast the display, set up the following:
4.1 In Tax Zones and Rates  create two rates,  for Canada - QC, Rates 5 and 9.975
4.2 In Tax Rules create two,  one for  the 9.975 one for the 5, have the priorities differ and set to calculate off subtotal only
5 Disable Avalara, and go to checkout, view that 9.975 shows instead of 9.98
### Expected result

1.  Tax should not be rounded as such, or options should be provided to specify the precision.

### Actual result

1.  Tax comes in from Avalara correctly, 0.0975 / 9.975% 
2. Tax gets rounded somewhere in the module.
3. Tax Summary return in totals section during the update call is rounded
4. Remove Avalara and using Magento taxes correctly shows 9.975

Avalara Taxes:
![image](https://user-images.githubusercontent.com/19933966/45954483-1ec88180-bfdb-11e8-9006-3f6fe8a66835.png)

Ajax call  which shows that the percent is rounded before getting to the frontend
![image](https://user-images.githubusercontent.com/19933966/45955052-e9249800-bfdc-11e8-93ff-d309471e561a.png)

Magento Taxes:
![image](https://user-images.githubusercontent.com/19933966/45954857-348a7680-bfdc-11e8-8445-1e761a0ea853.png)

My Tax Config for testing core vs Avalara

![image](https://user-images.githubusercontent.com/19933966/45955088-022d4900-bfdd-11e8-8baa-cc19fe05c33c.png)

![image](https://user-images.githubusercontent.com/19933966/45955075-fc376800-bfdc-11e8-87b3-9048ab20fbd9.png)

**Comment by rsisco** [comment]
This issue has been addressed in release #[1.4.9](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.4.9). Closing issue.
