### ISSUE TITLE
Enabling module results in 500 error when loading /admin

### ISSUE THREAD

**Issue by casconed** [classyllama/ClassyLlama_AvaTax#18]
```
PHP Fatal error:  Class 'ClassyLlama\\AvaTax\\Helper\\Config' not found in /srv/www/magento/releases/201605250001/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 107
```

**Comment by casconed** [comment]
Version 0.2.3

**Comment by erikhansen** [comment]
Are you running in production mode? If so, have you run these commands:

```
rm -rf var/di/
bin/magento setup:di:compile
bin/magento setup:static-content:deploy
```

**Comment by casconed** [comment]
I ran those without error, after which I got the Fatal Error.

**Comment by erikhansen** [comment]
Did you install via Composer or by copying files?

**Comment by casconed** [comment]
Composer

**Comment by erikhansen** [comment]
Can you change Magento to run in developer mode and see if you get the same error? If you're using Apache, you can do this easily by uncommenting one of the first lines in the `.htaccess` file in the Magento root or /pub, depending on what you're using as your document root.

**Comment by casconed** [comment]
No error in developer mode!

**Comment by erikhansen** [comment]
Switch back to production mode and compile using this command:

```
bin/magento -- setup:di:compile-multi-tenant
```

**Comment by casconed** [comment]
Worked - thanks!

**Comment by erikhansen** [comment]
There is a known issue with the single-tenant compiler; it does not currently compile proxies. Therefore, if you're preparing to deploy to production, you must use the multi-tenant compiler.
