### ISSUE TITLE
Shipping is zeroed out on Magento 2.2.6 using table rate

### ISSUE THREAD

**Issue by andrelundsett** [classyllama/ClassyLlama_AvaTax#184]
After upgrading to 2.2.6 in our dev environment, the Shipping cost is excluded from the Order total. If the shipping address is for a region where Avatax is not enabled, the shipping cost is included as expected. Also, if we disable Avatax, the shipping cost is correctly included. This problem did not happen on 2.2.5.

### Preconditions

1. Magento 2.2.6
2. Avatax 1.4.6
3. PHP 7.0.31
4. MySQL 5.7.23
5 CentOS 7

### Steps to reproduce

1. Add products to cart and go to checkout
2. Select table rate shipping option
3. Proceed to "Review & Payments"

### Expected result

1. The actual cost of the selected shipping option should be listed under Order Summary

### Actual result

1. There is a shipping line item under Order Summary, but the cost have been incorrectly set to $0.00. See screenshots.

![image](https://user-images.githubusercontent.com/4931990/46294082-47c9b300-c595-11e8-9729-19e5d5b931f9.png)

![image](https://user-images.githubusercontent.com/4931990/46294096-4f895780-c595-11e8-8f33-7bab4662d9a9.png)

**Comment by rsisco** [comment]
This issue has been confirmed to occur beginning in Magento 2.2.6 and 2.1.15 with multiple shipping methods.

**Comment by rsisco** [comment]
I've merged code that addresses this issue. I've confirmed the fix (and its backwards compatibility) by testing with multiple versions of Magento 2.1.x and 2.2.x both with taxed and untaxed shipping codes.

**Comment by rsisco** [comment]
@andrelundsett - I just published release #[1.4.7](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.4.7) that fixes this issue. Closing issue.

**Comment by andrelundsett** [comment]
@rsisco - Thank you for the quick turnaround on this issue!
