### ISSUE TITLE
Avatax appears to break Swagger schema generation

### ISSUE THREAD

**Issue by JamesonNetworks** [classyllama/ClassyLlama_AvaTax#19]
M2 can generate Swagger information about the API via "http://127.0.0.1/index.php/rest/default/schema". When the Avatax module is installed, this route throws an exception with the error message:

Class "storeId" does not exist. Please note that namespace must be specified.

And the stack trace:

#0 /Sites/magento2ee/vendor/magento/module-webapi/Model/Config/ClassReflector.php(91): Magento\Framework\Reflection\TypeProcessor->register('storeId')
#1 /Sites/magento2ee/vendor/magento/module-webapi/Model/Config/ClassReflector.php(72): Magento\Webapi\Model\Config\ClassReflector->extractMethodData(Object(Zend\Code\Reflection\MethodReflection))
#2 /Sites/magento2ee/vendor/magento/module-webapi/Model/ServiceMetadata.php(114): Magento\Webapi\Model\Config\ClassReflector->reflectClassMethods('ClassyLlama\\Ava...', Array)
#3 /Sites/magento2ee/vendor/magento/module-webapi/Model/ServiceMetadata.php(142): Magento\Webapi\Model\ServiceMetadata->initServicesMetadata()
#4 /Sites/magento2ee/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(72): Magento\Webapi\Model\ServiceMetadata->getServicesConfig()
#5 /Sites/magento2ee/vendor/magento/module-webapi/Controller/Rest.php(234): Magento\Webapi\Model\AbstractSchemaGenerator->getListOfServices()
#6 /Sites/magento2ee/vendor/magento/module-webapi/Controller/Rest.php(158): Magento\Webapi\Controller\Rest->processSchemaRequest()
#7 /Sites/magento2ee/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /Sites/magento2ee/vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /Sites/magento2ee/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#10 /Sites/magento2ee/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#11 {main}

**Comment by erikhansen** [comment]
@JamesonNetworks Thanks for reporting this issue! It has been fixed in the latest release: https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/0.2.4
