### ISSUE TITLE
When AvaTax is Enabled Many Customer Options are Removed

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#195]
When customer enables the AvaTax module in M2 many of their customer options are removed. See images.
{}Account Name:{} Jayson Home Store
{}Account Number(s):{} 2000003442
{}Company Code(s):{} JH6
{}ERP Version:{} Magento M2
{}AvaTax Integration Version:{}
{}AvaTax Adapter Version:{}
{}OS/Browser Version:{}
{}Repro Frequency{}

{}Description:{} Customer is seeing his customer record being altered when enabling AvaTax. Many customer options disappear once AvaTax module is enabled.

{}Steps to Reproduce:{}
We disable module, clear cache then review the customer record; all menu items are present.
We enable module and review customer record; majority of menu items have disappeared.

{}Expected Result:{}
Customer record unchanged after module is enabled

{}Actual Result:{}
Customer record is missing many options after enabling AvaTax

{}Attachments/Documentation:{}
See images
![image](https://user-images.githubusercontent.com/29284849/47186288-fb94a780-d2e4-11e8-8cfe-5b09bbdad85d.png)

![image](https://user-images.githubusercontent.com/29284849/47186297-03544c00-d2e5-11e8-9997-369ae2ef49da.png)

**Comment by rsisco** [comment]
@joshuaqueenava - This issue should be resolved with version [1.4.8](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.4.8) of the extension. Please have the merchant upgrade their extension version and reopen this issue if the problem persists.
