### ISSUE TITLE
Fatal Error on Installation - Cannot allocate memory

### ISSUE THREAD

**Issue by sfxdotcom** [classyllama/ClassyLlama_AvaTax#212]
We have been trying to install AvaTax and have followed the steps in the documentation exactly.  When running the commands in the composer, we're receiving the following error:

```
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 844111872) (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php on line 126
```

We've increased the memory limit to the max our server would allow and still nothing.  Any idea what we can do to resolve this?

**Comment by rsisco** [comment]
@sfxdotcom - This doesn't seem to be an issue related to the AvaTax extension. Are you able to install other extensions via composer without issue?

**Comment by rsisco** [comment]
Closing this issue due to no response and the fact that it likely is not related to this specific extension.
