### ISSUE TITLE
Shipping Calculated on Website but Not AvaTax

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#217]
{*}Account Name:{*} 
{*}Account Number(s):{*} 
{*}Company Code(s):{*} 
{*}AvaTax Environment:{*} ash01 
{*}ERP Version:{*} Magento 2.2.6 Enterprise - AvaTax 1.4.9 
{*}AvaTax Integration Version:{*} 
{*}AvaTax Adapter Version:{*} 15.5.1.0 
{*}OS/Browser Version:{*} 
{*}Repro Frequency{*} 

{*}Description:{*} SO are charging tax on the freight but when it comes over to the AvaTax admin console - it only charges tax on the item -- for the state of CA, they are not suppose to be charging tax on the freight. 

The customer is already being charged and it's being billed on the credit card. 

{*}Steps to Reproduce:{*} Ran an audit - see attachment 
Had him create a test transaction. SO shows that there is tax on the freight but once committed as an invoice the tax is only on the item. 

Created SO - 1955 -- it charged 1.22 but on the invoice doc code #13000000209123-54367032883 
it only charge .19. 

{*}Expected Result:{*} To have both the SO & Invoice to show tax only on the item and not on the frieght. 

{*}Actual Result:{*} Tax is being charged on the freight on the SO but not on the Invoice. 

{*}Attachments/Documentation:{*} Video - https://avalara1-my.sharepoint.com/:v:/g/personal/joshua_queen_avalara_com/Edenytz-WBxJr0ZYop8n2eEBKK3tcfphY3g6Zsh0IJrGbA?e=zgTNHq

**Comment by joshuaqueenava** [comment]
[AsHangingSOAPOut.txt](https://github.com/classyllama/ClassyLlama_AvaTax/files/2691758/AsHangingSOAPOut.txt)
[AsHangingSOAPIn.txt](https://github.com/classyllama/ClassyLlama_AvaTax/files/2691759/AsHangingSOAPIn.txt)

**Comment by rsisco** [comment]
An internal ticket has been opened to look into this.

**Comment by joshuaqueenava** [comment]
@rsisco are there any updates on this ticket? Customer is pinging me for updates. Thank you.

**Comment by rsisco** [comment]
@prestonchoate - I'll let you take the lead on this one.

**Comment by prestonchoate** [comment]
@joshuaqueenava The internal ticket for this issue is projected to start work next week.

**Comment by prestonchoate** [comment]
@joshuaqueenava This one is really strange. From the video you captured I can't see how the shipping cost was being taxed. Could you get the user to enable debug level logging from the Magento admin, then trigger an order that has this issue, and then finally send me a copy of var/log/avatax.log? I cannot recreate this locally and it is pretty baffling as to how it could happen. I may need to work with the user directly to get access to a stage site or something to debug further.

**Comment by joshuaqueenava** [comment]
Requested details from customer. Said he would get it done and get back to me. Sending reminder email, case may end up closed if they do not respond within 7 days.

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com
