### ISSUE TITLE
Wrong Tax cal when some item of cart contain virtual products.

### ISSUE THREAD

**Issue by sunilit42** [classyllama/ClassyLlama_AvaTax#22]
Hey,

Very good module and code.

One bug i found this module : When cart contain both items like virtual and simple. Tax cal for all items it is not excluded virtual product.

Same for if the whole cart is virtual.

is there any solution for that?

**Comment by erikhansen** [comment]
@sunilit42 The AvaTax module sends all products to the tax calculation API, regardless of their product type. Some jurisdictions charge tax for virtual products, so it was not feasible to build the logic into the AvaTax extension to determine what product types to send to the API.

However if you don't want Virtual Products to be taxed, you can setup a Product Tax Class in Magento and then assign that tax class a an "AvaTax Tax Code" that will make that tax class untaxable. See this section of the documentation for details on how to setup Product Tax Classes: http://www.classyllama.com/documentation/extensions/avatax-magento-2-module#product-tax-codes You would then assign all of the Virtual Products to the newly created Tax Class.

You can see some of the AvaTax tax codes in the "What are AvaTax System tax codes?" section of this page: https://help.avalara.com/000_AvaTax_Calc/000AvaTaxCalc_User_Guide/051_Manage_Product_Taxability/010_Select_AvaTax_System_Tax_Codes/Tax_Codes_-_Frequently_Asked_Questions

**Comment by sunilit42** [comment]
Hello,
thanks for reply.

As you said i created new product tax class and name of class is AvaTax Tax Code and assign tax class to the product but still your module does not exclude from tax calculation.

![fireshot capture 1 - gift card _ products _ inventory _ pro_ - http___realmealdelivery magemojo co](https://cloud.githubusercontent.com/assets/2923438/16256191/d66c8112-386d-11e6-8042-5ec06545ec5e.png)

**Comment by erikhansen** [comment]
@sunilit42 Can you reach out to your Avalara support rep for help in configuring specific products to not have tax calculated?

**Comment by sunilit42** [comment]
@erikhansen even quote is virtual then no need to call request to api.

**Comment by erikhansen** [comment]
@sunilit42 Unfortunately the extension doesn't support the workflow you're describing.

**Comment by loganstellway** [comment]
Hi @sunilit42 

We recently had a case where we had a wholesale item we did not want to charge tax on. To solve this: from within Avalara's admin console, **map the item** & apply the **NT** tax code. 

Reference Articles:
  - [How to Make an Item Nontaxable](https://help.avalara.com/Frequently_Asked_Questions/001/How_do_I_make_an_item_nontaxable%3F)
  - [Find the right tax codes](https://help.avalara.com/Frequently_Asked_Questions/Product_Taxability_FAQ/Where_can_I_get_help_finding_the_right_tax_code%3F)

**Comment by sunilit42** [comment]
@loganstellway make it not taxable that product
