### ISSUE TITLE
1.4.9 Not Working After Upgrade to 2.2.7

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#220]
{*}Account Name:{*} 
{*}Account Number(s):{*} 
{*}Company Code(s):{*} 
{*}ERP Version:{*} Magento Community 2.2.7
{*}AvaTax Integration Version:{*} ClassyLlama 1.4.9
{*}AvaTax Adapter Version:{*} N/A
{*}OS/Browser Version:{*} Windows/Chrome
{*}Repro Frequency{*} 100%

{*}Description:{*} We are running into an odd issue that I've not seen before. We had your 
extension installed in both our staging and production environments with no 
problems. Recently we upgraded to 2.2.7 in both of those environments. 
After the upgrade the Avatax options are not showing under 
Stores->Configuration->Sales->Tax. When I went to troubleshoot, the 
extension isn't even listed when I run bin/magento module:list. I've tried 
running setup:upgrade again with no luck. I've also got the same problem 
locally, so I tried deleting my entire vendor directory and running a fresh 
composer install. Same issue. 

Sorry for the long winded description but I've never had this happen before 
and I'm not seeing anything that I can tell would cause it. Not noticing it 
with any of our other composer modules. Have you guys run across any issues 
with 2.2.7? Any ideas what is causing the strange behavior?

{*}Steps to Reproduce:{*} Attempt to install 1.4.9 from composer

{*}Expected Result:{*} Install/update successful

{*}Actual Result:{*} 

{*}Attachments/Documentation:{*}

**Comment by joshuaqueenava** [comment]
Recorded meeting: https://avalara1-my.sharepoint.com/:v:/g/personal/joshua_queen_avalara_com/Ea3_tJg3hoNOpZWFhv5vdUwBtk_92de90vp2sUJEZf3Fpw?e=jnCYcA

**Comment by joshuaqueenava** [comment]
Any updates on this ticket? @rsisco

**Comment by prestonchoate** [comment]
@joshuaqueenava The internal task for this is on my list of things to look into this week. I have a couple of other things ahead of this one currently, but can you get me in touch with the user? This is one where I will likely have to work directly with them in order to determine what is happening. We have used this extension on 2.2.7 and haven't seen this issue.

**Comment by joshuaqueenava** [comment]
@prestonchoate did you get a chance to work with Cody on this? I don't see anything after I put the two of you in touch. Just checking as I am updating my case.

**Comment by joshuaqueenava** [comment]
Pinging customer again. If he does not respond within 7 days, case will close automatically.

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com
