### ISSUE TITLE
Billing Address Changes to Shipping Address when "Same as Billing" checked After Validating (On frontend)

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#221]
{*}Account Name:{*} Better Planet Brands LLC/ Acure Organics 
{*}Account Number(s):{*} 1100102144 
{*}Company Code(s):{*} 3872663 
{*}AvaTax Environment:{*} PROD 
{*}ERP Version:{*} Magento 2.2.4 Community - AvaTax 1.5.0 
{*}AvaTax Integration Version:{*} 
{*}AvaTax Adapter Version:{*} 15.5.1.0 
{*}OS/Browser Version:{*} Chrome 
{*}Repro Frequency{*} ALL 

{*}Description:{*} 
We are experiencing an issue on our checkout page at acure.com <http://acure.com/> where if the client ha a different billing address other than the shipping address and tries to input the new address, Avatax reverts the new billing back to the shipping address because of the Address Validation setting in the config feel for your module in Magento 2. 

Once we disable this option >>> Address Validation 
The checkout works as it should be. 

Can we install a third party address verification module to handle this or is there a better solution on your end. 

We’ve updated the module to your latest version and we are still receiving the same error. Please advise. 

{*}Steps to Reproduce:{*} See above 

{*}Expected Result:{*} Expects the address entered to be the one that is used for calculation 

{*}Actual Result:{*} The system ins reverting the billing address back to the shipping address 

{*}Attachments/Documentation:{*}

**Comment by joshuaqueenava** [comment]
Video recording of issue.

https://avalara1-my.sharepoint.com/:v:/g/personal/joshua_queen_avalara_com/ER19iPUtDhdAgH7lcKNqWNQBOP8lu_AW-kBZkc-svvFT7Q?e=Ug9At6

**Comment by joshuaqueenava** [comment]
Has there been any analysis on this issue? Customer is requesting an update. Thank you.

**Comment by prestonchoate** [comment]
@joshuaqueenava This customer is utilizing a custom one step checkout that is most likely causing this issue. I have been speaking with them via email and have informed them of the situation.
