### ISSUE TITLE
Shipping Method Changing When "Same as Billing" Checked

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#222]
{*}Account Name:{*}
{*}Account Number(s):{*} 
{*}Company Code(s):{*} 
{*}AvaTax Environment:{*} DEV 
{*}ERP Version:{*} Magento 2 
{*}AvaTax Integration Version:{*} 
{*}AvaTax Adapter Version:{*} 
{*}OS/Browser Version:{*} Chrome 
{*}Repro Frequency{*} ALL 

{*}Description:{*} I'm currently doing some testing with the Avatax extension for Magento 
2.2.5 and I am currently experiencing some issues with some shipping 
methods not showing up when creating an Order from the Admin Panel 

When Avatax is set to Estimate Tax AND the checkbox "Same as Billing 
Address" is checked (for the Shipping Address) when creating the Order, the 
Free Shipping method doesn't show up. Leaving the checkbox unchecked shows 
the Free Shipping method as normal 

I've deduced it to be tied to Avatax as disabling Avatax entirely (or 
setting it to do nothing with Tax) fixes the issue and Free Shipping shows 
whether or not the "Same as Billing Address" is checked. 

{*}Steps to Reproduce:{*} See above 

{*}Expected Result:{*} Expects the FREE SHIPPING to kick in when the item is over 99$ 

{*}Actual Result:{*} This does not appear to be functioning 

{*}Attachments/Documentation:{*} Screenshot 

Hey Sean 

The project is currently on Magento version 2.2.7 and still does not work properly. 

Thanks, 
Nick

**Comment by joshuaqueenava** [comment]
Any updates on this ticket?

**Comment by calabanzas** [comment]
Hello,

We encountered the same issue when creating order in the admin, the Free Shipping only shows up when unchecking the Same As Billing Address and it will not show when checking the Same As Billing Address.

And on our investigation, the issue only occurs when ClassyLlama_AvaTax module is enabled.

Magento version is 2.2.4

Thanks,
Camille

**Comment by joshuaqueenava** [comment]
@prestonchoate can you raise the priority on this ticket, please? This is aging and a second customer has reported this issue. I would consider this high priority if that's possible. Thanks!

**Comment by joshuaqueenava** [comment]
Was there work done on this ticket before we began the transition? Customer is requesting updates from the Avalara team. @prestonchoate

**Comment by prestonchoate** [comment]
@joshuaqueenava No work ever began on our side for this one.

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com
