### ISSUE TITLE
AvaTax Not Working - Latest Version (1.5.0)

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#223]
{*}Account Name:{*} Naturepedic 
{*}Account Number(s):{*} 2000006769 Prod and 2000191900 Sandbox 
{*}Company Code(s):{*} SFHP for Prod and Naturepedic for 
{*}AvaTax Environment:{*} Both Prod and Sandbox 
{*}ERP Version:{*} Magento 2- Although connector signature report has Magento 1.8.1.0 
{*}AvaTax Integration Version:{*} Magento 1.8.0 
{*}AvaTax Adapter Version:{*} Magento 1.8.0 
{*}OS/Browser Version:{*} 
{*}Repro Frequency{*} 

{*}Description:{*} 
magento 2 user getting no tax calculation in their online store. See screenshot. 

acct# and license key validate, company code is correct. Screenshot attached. 

I made sure that the ship-to address validates and is in a nexus state: 
195 Broadway 
New York, NY 10007 

from 1/3/19- 

This custoemr called back in regarding this matter; they are rporting in their sandbox, 2000191900 their acct is not validating addresses getting this error "	There is missing or incorrect information. See Details below and complete the form.
Service not enabled.'" confirmed that their AvaTax Calc was not enabled in sandbox 
created a new case as well 15877269 for the connector 

customer reporting that their 2000006769 is still not connecting, however it is, appaerently the issue appaers to be that their new Magento is not connecting 

tried reviewing the https://github.com/classyllama/ClassyLlama_AvaTax/blob/develop/docs/getting-started.md to configure 

we went through this link as well 
https://raw.githubusercontent.com/classyllama/ClassyLlama_AvaTax/develop/docs/images/configuration_screenshot_2.0.0-rc1.png 

{*}Steps to Reproduce:{*} 
from 12/19/18- 

i turned on an audit but got no tax call from Magento2 

From 1/3/19 

we went through their settings etc and still not able to to push a tranasction through as well 
\Customer case was originally assigned to our Tier 2 tech support team however it appears to have gottenre-assigned a couple of times so looks to have been lost in the shuffle 

{*}Expected Result:{*} 

{*}Actual Result:{*} 

{*}Attachments/Documentation:{*}

**Comment by joshuaqueenava** [comment]
Are there any updates on this ticket? @prestonchoate

**Comment by prestonchoate** [comment]
I think I actually talked to this person via our direct support email. Can you verify that I resolved his issue? The taxable countries config value was not being retrieved correctly on his site for some odd reason. I advised him to just set the values in the admin for that at the store level and it resolved the problem.
