### ISSUE TITLE
Base Grand Total and Grand Total contain diffrrent value

### ISSUE THREAD

**Issue by toddliningerdesign** [classyllama/ClassyLlama_AvaTax#23]
After install module base grand total and grand total value different on checkout page.

{"payment_methods":[{"code":"inchoo_stripe","title":"Stripe"},{"code":"free","title":"No Payment Information Required"}],"totals":{"grand_total":31,"base_grand_total":33.17,"subtotal":31,"base_subtotal":31,"discount_amount":0,"base_discount_amount":0,"subtotal_with_discount":31,"base_subtotal_with_discount":31,"shipping_amount":0,"base_shipping_amount":0,"shipping_discount_amount":0,"base_shipping_discount_amount":0,"tax_amount":2.17,"base_tax_amount":2.17,"weee_tax_applied_amount":null,"shipping_tax_amount":0,"base_shipping_tax_amount":0,"subtotal_incl_tax":33.17,"shipping_incl_tax":0,"base_shipping_incl_tax":0,"base_currency_code":"USD","quote_currency_code":"USD","items_qty":5,"items":[{"item_id":3912,"price":5,"base_price":5,"qty":2,"row_total":10,"base_row_total":10,"row_total_with_discount":0,"tax_amount":0.7,"base_tax_amount":0.7,"tax_percent":7,"discount_amount":0,"base_discount_amount":0,"discount_percent":0,"price_incl_tax":5.35,"base_price_incl_tax":5.35,"row_total_incl_tax":10.7,"base_row_total_incl_tax":10.7,"options":"[]","weee_tax_applied_amount":null,"weee_tax_applied":null,"name":"BBQ Chicken Skewers"},{"item_id":3913,"price":7,"base_price":7,"qty":3,"row_total":21,"base_row_total":21,"row_total_with_discount":0,"tax_amount":1.47,"base_tax_amount":1.47,"tax_percent":7,"discount_amount":0,"base_discount_amount":0,"discount_percent":0,"price_incl_tax":7.49,"base_price_incl_tax":7.49,"row_total_incl_tax":22.47,"base_row_total_incl_tax":22.47,"options":"[]","weee_tax_applied_amount":null,"weee_tax_applied":null,"name":"Beef Satay w\/Asian Sesame BBQ Sauce"}],"total_segments":[{"code":"subtotal","title":"Subtotal","value":31},{"code":"shipping","title":"Shipping & Handling","value":0},{"code":"tax","title":"Tax","value":2.17,"area":"taxes","extension_attributes":{"tax_grandtotal_details":[{"amount":2.17,"rates":[{"percent":"4","title":"GA STATE TAX"},{"percent":"3","title":"GA COUNTY TAX"}],"group_id":1}]}},{"code":"grand_total","title":"Grand Total","value":33.17,"area":"footer"}}}

Please check response in browser console when you enter shipping information and select shipping method.

**Comment by erikhansen** [comment]
@toddliningerdesign Some questions for you:

1. Are you using more than one currency in your store?
2. What version of the AvaTax extension are you using?
3. What version and edition of Magento are you using (e.g., 2.1 Community)

**Comment by sunilit42** [comment]
Hello,
Are you using more than one currency in your store? : No

What version of the AvaTax extension are you using? :- setup_version="0.2.4"

What version and edition of Magento are you using (e.g., 2.1 Community) :- 2.0.7

**Comment by sunilit42** [comment]
@erikhansen todd and me both are working on same site.

**Comment by sunilit42** [comment]
which email id?

**Comment by erikhansen** [comment]
@sunilit42 I included my email address in my previous comment and then redacted it a few minutes after posting the comment. If you get email notifications from Github, you should have it in your email. If not, can you post your email here and I'll send you an email?

**Comment by erikhansen** [comment]
@sunilit42 @toddliningerdesign Did you see my latest comment?

**Comment by toddliningerdesign** [comment]
Yes, we found your email address. I will have Sunil email you. Thank you.

**Comment by erikhansen** [comment]
Per our email thread, I looked into this issue and determined it was a Magento bug, not an AvaTax issue, that was causing the issue.

**Comment by erikhansen** [comment]
FYI, I tested this on native Magento 2.1 with sample data. It had the same behavior:

![15-18-27 checkout-5nmf6](https://cloud.githubusercontent.com/assets/129031/16745346/0651f44a-477b-11e6-8396-fe55856a12f2.png)


![quote-c6nob](https://cloud.githubusercontent.com/assets/129031/16745392/3b898a1a-477b-11e6-8235-ab356cac4a2d.png)

![sales_order-9rnip](https://cloud.githubusercontent.com/assets/129031/16745426/61be1bba-477b-11e6-9164-88e35d66789b.png)

**Comment by lano-vargas** [comment]
@erikhansen Do you know anything else about it any fix I know it isn't related to Avatax issue But have you came across a fix pleas share thanks

**Comment by erikhansen** [comment]
@lano-vargas Unfortunately I don't have any more info on this bug. I would recommend searching the open and closed issues here: https://github.com/magento/magento2/issues
