### ISSUE TITLE
Multiple sources (warehouses) doesn't send different origin

### ISSUE THREAD

**Issue by sevenpixels** [classyllama/ClassyLlama_AvaTax#230]
### Preconditions
1. Magento 2.3EE
2. AvaTax 1.5

### Steps to reproduce

1. Set up multiple sources
2. Apply source specific products, only 1 source per product
3. Place order with multiple items, all different sources

### Expected result

1. I should see different origins for each of the line items in Avalara.

### Actual result

1. Each line item has the default origin that is input in Configuration -> Sales -> Shipping Settings

![image](https://user-images.githubusercontent.com/502377/52224908-07898280-285e-11e9-93d4-81ae68860190.png)
![image](https://user-images.githubusercontent.com/502377/52225011-40c1f280-285e-11e9-9ca6-5e1ccb65f44d.png)

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com

Sorry for the delay in replying to this issue.
