### ISSUE TITLE
Tax Being Subtracted from Line Items for Monaco

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#232]
{*}Account Name:{*} 
{*}Account Number(s):{*}
{*}Company Code(s):{*} 
{*}AvaTax Environment:{*} PROD 
{*}ERP Version:{*} Magento 2.2.6 Enterprise - AvaTax 1.4.9 
{*}AvaTax Integration Version:{*} 
{*}AvaTax Adapter Version:{*} 15.5.1.0 
{*}OS/Browser Version:{*} Chrome 
{*}Repro Frequency{*} 

{*}Description:{*} Tax is removed from the taxable items when they advance to the Payment screen. 

{*}Steps to Reproduce:{*} go to 

Delivery address: 14 Gowers Walk 
London, 98000 
MONACO 

Add item to BAG 
TAX should show untill you click to the payment screen 

{*}Expected Result:{*} Expects that tax is calculated as they have nexus in Monaco 

{*}Actual Result:{*} Tax is not calculating 

{*}Attachments/Documentation:{*}

**Comment by joshuaqueenava** [comment]
https://avalara1-my.sharepoint.com/:v:/g/personal/joshua_queen_avalara_com/EXApa7FHzD1Imiy4eoIK8ysBvTyoPMmH79VDYcn0OLxt9g?e=QuBIUE

**Comment by joshuaqueenava** [comment]
@prestonchoate are there updates on this issue? Can you set this to high priority, please?

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com

Sorry for the delay in replying to this issue.
