### ISSUE TITLE
AvaTax & Magento 2: Order Cancellation Urgent Issue - ref:_00D30Psz._5000b1P3zlZ:ref

### ISSUE THREAD

**Issue by joshuaqueenava** [classyllama/ClassyLlama_AvaTax#233]
{*}Account Name:{*} 
{*}Account Number(s):{*} 
{*}Company Code(s):{*} 
{*}ERP Version:{*} Magento 2.1 
{*}AvaTax Integration Version:{*} 
{*}AvaTax Adapter Version:{*} 
{*}OS/Browser Version:{*} Windows/Chrome 
{*}Repro Frequency{*} Low 

{*}Description:{*} Customer is seeing some transactions being canceled without authorization or anyone canceling them: 

"	
Hello Support, 

In working in -------------, we discovered an unusual and Urgent issue regarding Avatax. It appears that for some reason Avatax is marking orders as Canceled, even though they have been Shipped and Invoiced. 

We are using Magento ver 2.1.7 Cloud 

Please find our example attached. Please let me know what other information I should provide. 

--------
Project Manager" 

{*}Steps to Reproduce:{*} Review Order Sync Queue 
Observe canceled orders 

{*}Expected Result:{*} Orders are only canceled when appropriate or performed by Magento Admin User(s). 

{*}Actual Result:{*} 

{*}Attachments/Documentation:{*}

**Comment by alliduncan** [comment]
@joshuaqueenava The issue above references an example attached, but I don't see an attachment. Also, per our phone conversation yesterday, we determined there is no actionable item for Classy Llama at this time. We recommended the merchant use a higher debugging setting to identify issues should they happen again. Please confirm.

**Comment by joshuaqueenava** [comment]
@alliduncan I inquired as to whether Classy Llama wanted a ticket open for this issue. I had opened this because the Classy Llama team asked that I do open a ticket.

**Comment by alliduncan** [comment]
@joshuaqueenava Gotcha. No worries. I just wanted to make sure. Thanks.

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com

Sorry for the delay in replying to this issue.
