### ISSUE TITLE
Compilation error for 2.0.0-beta and RC release

### ISSUE THREAD

**Issue by santhoshnsscoe** [classyllama/ClassyLlama_AvaTax#237]
We installed the 2.0.0-RC1 and 2.0.0-beta2 releases and both of them give compilation error.

### Preconditions
1. Magento 2.2.7
2. php 7.1

### Steps to reproduce
1. Install the module via composer require classyllama/module-avatax 2.0.0-RC1
2. Then run php bin/magento setup:upgrade
3. php bin/magento setup:di:compile

### Expected result
1. Everything works fine and the compilation is finished 100%

### Actual result
1. Compilation error.

```
php bin/magento setup:di:compile 
Compilation was started.
Interception cache generation... 6/7 [========================>---]  85% 22 secs 348.0 MiBErrors during configuration scanning:
    Avalara\TransactionBuilderFactory
        Invalid Factory for nonexistent class Avalara\TransactionBuilder in file /var/www/html/public_html/vendor/classyllama/module-avatax/Framework/Interaction/Rest/Tax.php
Total Errors Count: 1


  [Magento\Framework\Validator\Exception]  
  Error during compilation                 


setup:di:compile
```

**Comment by erikhansen** [comment]
@dewayneholden Can you post what you did to get this working on the project you were working on?

**Comment by erikhansen** [comment]
@santhoshnsscoe Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com

Sorry for the delay in replying to this issue.
