### ISSUE TITLE
PHP version 7.2.14 composer install fail

### ISSUE THREAD

**Issue by oobehub** [classyllama/ClassyLlama_AvaTax#238]
Trying to install classyllama/module-avatax:2.0.0-RC1 via composer.

### Preconditions
1. Magento 2.3.0
2. PHP 7.2.14

### Steps to reproduce
1.  composer require classyllama/module-avatax:2.0.0-RC1

### Actual result
Problem 1
    - magento/framework 101.0.7 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.16 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.6 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.15 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.14 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.4 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.13 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.3 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.12 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.2 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.11 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.0 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.1 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - classyllama/module-avatax 2.0.0-RC1 requires magento/framework ^100.1.0|101.0.* -> satisfiable by magento/framework[100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12, 101.0.3, 100.1.13, 101.0.4, 101.0.5, 100.1.14, 100.1.15, 101.0.6, 100.1.16, 101.0.7].
    - Installation request for classyllama/module-avatax 2.0.0-RC1 -> satisfiable by classyllama/module-avatax[2.0.0-RC1].

This is odd because we have installed other modules via composer.  The output makes it seem like Magento framework doesn't support PHP 7.2.X, but it does.

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com.
