### ISSUE TITLE
Version Upgrade-1.5.3-Magento_Checkout/js/model/shipping-save-processor/payload-extender.min.js-404 Error

### ISSUE THREAD

**Issue by pioneerathletics** [classyllama/ClassyLlama_AvaTax#240]
### Preconditions

1. Magento version 2.1.14
2. AvaTax version 1.5.3

### Steps to reproduce

1. Manually upgraded AvaTax version to 1.5.1 
2. Received 404 error for Magento_Checkout/js/model/shipping-save-processor/payload-extender.min.js
3. Manually upgraded Avatax version to 1.5.3 to see if latest version would fix problem
4. Received 404 error again for Magento_Checkout/js/model/shipping-save-processor/payload-extender.min.js

### Expected result

1. Extension should update fine

### Actual result

1. Received 404 error for Magento_Checkout/js/model/shipping-save-processor/payload-extender.min.js

**Comment by erikhansen** [comment]
Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com

Sorry for the delay in replying to this issue.
