### ISSUE TITLE
Error for creditmemo

### ISSUE THREAD

**Issue by riyajalijunakiya** [classyllama/ClassyLlama_AvaTax#241]
### Preconditions

1. Magento 2.2.6, AvaTax 1.4.7
2. 

### Steps to reproduce

1. Creditmemo type queue not processed. http://prntscr.com/mu4j34
2. It give error of store not found http://prntscr.com/mu4s8j
3.

### Expected result

1.It should processed and not give store error. 

### Actual result

1. [Screenshot, logs]
Not processed and giving store error
http://prntscr.com/mu4j34
http://prntscr.com/mu4s8j

When I debug code I have found that it give null value in $object->getStoreId(); in ClassyLlama/AvaTax/Framework/Interaction/Tax.php in function getGetTaxRequestForSalesObject($object) when objectType is creditmemo.

All invoice proceed well but all creditmemos  stucks and not proceed.

**Comment by erikhansen** [comment]
@riyajalijunakiya Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com

Sorry for the delay in replying to this issue.
