### ISSUE TITLE
RMA is not posting to AvaTax

### ISSUE THREAD

**Issue by devendracorra** [classyllama/ClassyLlama_AvaTax#242]
### Preconditions

1. Magento version: 2.1.10
2. AvaTax version: 

### Steps to reproduce

1. Create RMA from Admin
2. It used to post RMA to AvaTax
3. It stopped posting since 17th March

### Expected result

1. It should post RMA to AvaTax.

### Actual result

1. [Screenshot, logs]
Recently it's been reported that whenever  creating Returns (RMA) from Magento Admin, it is not getting communicated with Avalara.com
Regular order invoices are getting reflected correctly there. 

This issue started after 17th Feb 2019. We didn't have any specific deployment prior to that regarding this. We contacted Avalara.com and they checked their Audit trails and found that it is not connecting to Avalara.com when creating Returns in Magento.

**Comment by erikhansen** [comment]
@devendracorra Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com

Sorry for the delay in replying to this issue.
