### ISSUE TITLE
When a state is not enabled in Avalara, its not pulling the rate from Magento

### ISSUE THREAD

**Issue by dsalgaciello** [classyllama/ClassyLlama_AvaTax#243]
### Preconditions

1. Magento Enterprise 2.1.16
2. PHP 7.1.27
3. Mysql MariaDB 10.0.32

### Steps to reproduce

1. if a state is not enabled in Avalara, it does not display any tax rates at all in the cart or checkout, even if there is a tax rule for that state in the magento admin that it should be falling back to although we have the setting to fall back to magento  native tax calculation.

2. In the extension configuration section avatax-advanced error Handling setting there is a the error section, which defines what to if there is an error when retrieving taxes from the avatax api. Here you have two options: once is Disable checkout & show error message - with this option the extension will prevent users and admins from placing orders. We have chosen: "allow checkout & fall back to native magento tax calculation (no error message)", so it should allow to default back to magento native without errors, when there is no state tax are not set in avalara. Is that correct? or am I missing something? The extension is suppose to allow fallback to magento native tax rules and allow users and admins to place an order without errors. 

### Expected result

1. with the error handling set to "allow checkout & fall back to native magento tax calculation (no error message)", it should fall back to magento native tax rules without errors, when there is no state tax are not set in avalara and allow users and admins to place an order without errors. 

### Actual result

1. it does not display any tax rates at all in the cart or checkout

**Comment by erikhansen** [comment]
@dsalgaciello Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com

Sorry for the delay in replying to this issue.
