### ISSUE TITLE
Calculated tax is shown as 0.00

### ISSUE THREAD

**Issue by rg-srini** [classyllama/ClassyLlama_AvaTax#246]
We are in the process of upgrading our store from Magento 2.1.4 to Magento 2.3 (Cloud Commerce). As part of this process, we have updated Classyllama avatax module to version 1.5.3 via composer.

Now, with the newer version, we are having an issue on showing calculated tax on view cart and checkout sections. When the page loads, on View Cart and Checkout Screens, we see the calculated tax ($ x.xx - appears for 1 or 2 seconds), but when the page is rendered, the tax value is shown as 0.00. 

When we checked the logs, the soap response shows the correct calculated tax. The checkout step 2 shows the grand total without Tax. But during order placement, the tax is calculated and updated correctly to the order and the same is captured at PG.

We checked this behavior on both Luma and our custom theme. This error causes confusion to the customer on the order grand total.

Could you please let us know the cause and fix for this issue?

**Comment by prestonchoate** [comment]
@rg-srini Avalara has shifted how they are handling support for this extension and are no longer providing support via Github issues. If you are still experiencing this issue, please contact support@avalara.com
