### ISSUE TITLE
compiling error with pre-release version 0.1.12

### ISSUE THREAD

**Issue by inspiredchu** [classyllama/ClassyLlama_AvaTax#3]
Not sure if error is due to this module, but I get the following error while recompiling magento (php bin/magento setup:di:compile)

> Compilation was started.
Area configuration aggregation... 5/7
[ErrorException]
ltrim() expects parameter 2 to be string, array given

apologies in advance if this is not a module issue.

**Comment by inspiredchu** [comment]
I think the bug is due to a error in the compilation process for single-tenant stores. I was able to finish the compilation by running the following command:

php bin/magento setup:di:compile-multi-tenant

**Comment by erikhansen** [comment]
Glad your issue was resolved. Magento has acknowledged that the single tenant compiler is not working currently. Closing ticket.
