### ISSUE TITLE
mapping avatax to magento

### ISSUE THREAD

**Issue by wzhou40555** [classyllama/ClassyLlama_AvaTax#30]
We have a Magento 2 installation using avatax extension.  We want to map the documents created in Avatax with the invoice or credit memo in Magento. From the documentation it looks like the transaction ID should map but it doesn't seem to. Can you please let us know how we can match up the two - Avatax + Magento.

**Comment by erikhansen** [comment]
@wzhou40555 Sorry for the delay in replying. I was out of the office for a couple of weeks. I don't really understand what you're asking, but I think this falls outside the scope of support for the extension. Can you email support@avalara.com for questions like this?

**Comment by mttjohnson** [comment]
It looks like the DocCode on the Avalara side includes the Invoice Increment ID from Magento
https://github.com/classyllama/ClassyLlama_AvaTax/blob/09b481b551fc55d937b496386c176972f177796f/Framework/Interaction/Tax.php#L612

For example I could have an order in Magento (Order # 000000005) and it could have an invoice (Invoice #000000006) and when the invoice is submitted to Avalara it gets a DocCode (000000006123-87594071520) that includes the Invoice Increment ID from Magento plus some additional appended numbers.
