### ISSUE TITLE
Installation fails because Class in required namespace doesn't exist in the library.

### ISSUE THREAD

**Issue by bangerkuwranger** [classyllama/ClassyLlama_AvaTax#31]
We've been attempting to install this module on both Magento 2.0.4 EE and 2.1.0 EE. In both environments, the module fails and we get an error:
`main.CRITICAL: Class AvaTax\ATConfigFactory does not exist`
The current packageist version of avalara/avatax includes a class ATConfig, but not the class named ATConfigFactory that is called in line 18 of ClassyLlama_AvaTax/Helper/Config.php.

**Comment by erikhansen** [comment]
Please delete `var/generation` and `var/di`.

If you are running in production mode, please make sure you run `bin/magento setup:di:compile` after installing the extension.

Please make sure you’ve followed all installation steps listed here: http://www.classyllama.com/documentation/extensions/avatax-magento-2-module

I had another merchant that ran into this issue and once they went back and followed all of the setup instructions, their issues were resolved.

**Comment by erikhansen** [comment]
@bangerkuwranger Were you able to get this working? If so, what steps did you take to get it working?

**Comment by erikhansen** [comment]
Closing issue due to lack of response.

**Comment by bangerkuwranger** [comment]
Yes, sorry for the response after such a long time... there were TWO issues our contractors needed to fix in order to get the module to compile: first (as listed in the install instructions) php7 soap was NOT installed, and second, they were attempting to flush and recompile without verifying the correct permissions on the magento folders, which left files in the generation directory and threw the same error. We wiped both directories completely clean and added the soap module for php7, and it compiled properly. Thanks!!

**Comment by erikhansen** [comment]
@bangerkuwranger Great, glad it's working for you.
