### ISSUE TITLE
Compilation fails on Magento 2.1.0 EE

### ISSUE THREAD

**Issue by ryannguyen** [classyllama/ClassyLlama_AvaTax#32]
I have followed the instructions for installation here: http://www.classyllama.com/documentation/extensions/avatax-magento-2-module

We are choosing to do "install by copying files".  After finishing installation, we run into the following error while trying to compile vis bin/magento setup:di:compile

```root@229e86ffc496:/var/www/magento# magento setup:di:compile
Compilation was started.
Application code generator... 3/7 [============>---------------]  42% 3 mins 172.0 MiBPHP Fatal error:  Class 'SoapClient' not found in /var/www/magento/vendor/avalara/avatax/AvaTax/DynamicSoapClient.php on line 21```

We are running Magento 2.1.0 EE

**Comment by erikhansen** [comment]
Your system likely doesn't have the PHP Soap extension installed. You'll need to enable/install it before AvaTax will work. http://stackoverflow.com/questions/11391442/fatal-error-class-soapclient-not-found

**Comment by ryannguyen** [comment]
@erikhansen thanks!

**Comment by kojimairiguchi** [comment]
Hi!  have the same issue, but I already have the SoapClient Extension on mi server

**Comment by rsisco** [comment]
@kojimairiguchi - Does `phpinfo();` display that the SOAP client is enabled as mentioned in the [previously provided link](https://stackoverflow.com/questions/11391442/fatal-error-class-soapclient-not-found)?

**Comment by kojimairiguchi** [comment]
![image](https://user-images.githubusercontent.com/235083/30065865-3f971eb6-9224-11e7-9bea-ba2c950ef7ad.png)
Yup. look at the attachment. 

```php
class WSSecuritySoapClient extends SoapClient
{
    private $useSSL = false;
    private $privateKey = "";
    private $publicCert = "";
    function __construct($wsdl, $privateKey, $publicCert, $options)
    {


        $locationparts = parse_url($wsdl);
        $this->useSSL  = $locationparts['scheme'] == "https" ? true : false;
        $this->privateKey = $privateKey;
        $this->publicCert = $publicCert;

        return parent::__construct($wsdl, $options);
    }
```

**Comment by kojimairiguchi** [comment]
my mistake, this is not the addon/plugin where I have the problem, sorry keep it close the issue
