### ISSUE TITLE
Two times capture amount for credit memo

### ISSUE THREAD

**Issue by sunilit42** [classyllama/ClassyLlama_AvaTax#36]
Hello,
when we do a refund,  it creates two entry 
Captured amount of $90.95 online Transaction ID ==> By default Magento doing that
We refunded $90.95 online. Transaction ID:  this is happening with your module when the queue is processed.

When queue is doing process below thing happening
please check below image,
http://easycaptures.com/fs/uploaded/1101/6941401048.png
why you are calling classyllama/module-avatax/Plugin/Sales/Model/Spi/CreditmemoResource.php,
and it is a calling payment, and doing capture amount offline again and so we can not create mutiple credit memo .

Please help us as soon as possible, we are big trouble due to module

**Comment by erikhansen** [comment]
@sunilit42 I'm not sure I completely understand this issue. Can you provide more detailed steps to reproduce? Also, can you review issue https://github.com/classyllama/ClassyLlama_AvaTax/issues/29 and let me know if this is the issue you're experiencing?

**Comment by sunilit42** [comment]
Hello Team, AvaTax Module doing credit Memo second time.

Let me explain how module doing.

When we generate credit memo in magento, magento capture amount,  your module submit request to avatex for credit back that amount.

That time it is called below function
ClassyLlama\AvaTax\Model\Queue\Task.php File
Function name processPendingQueue()
and it is called 
ClassyLlama\AvaTax\Model\Queue\Processing.php
There is one 
 $this->updateAdditionalEntityAttributes($entity, $processSalesResponse);
from there you are updating attribute into credit memo model and it will call your 
ClassyLlama\AvaTax\Plugin\Sales\Model\Spi\CreditmemoResource  and it is capture payment second time offline.
So it is calling second times.

So basically what you need to do, you need to modify updateAdditionalEntityAttributes function, i think you need to write custom query and do direct update into table, no need to save model again.

**Comment by erikhansen** [comment]
@sunilit42 I just merged in PR #41 to the develop branch, which fixes this issue. Before I issue a new release of this extension, can you verify that your issue is resolved by this fix?

**Comment by mttjohnson** [comment]
FYI: You can use composer to pull in the develop branch this way:
`composer require classyllama/module-avatax:dev-develop`

**Comment by erikhansen** [comment]
@sunilit42 Have you had a chance to test this yet?

**Comment by sunilit42** [comment]
@erikhansen  I think work based on below commit

https://github.com/classyllama/ClassyLlama_AvaTax/commit/84b57042eb6f3ce99e6f1b3a29391327342a9fcb


I already solved using other way so i can not able to test using your commit but it's works i checked your code.

**Comment by erikhansen** [comment]
This issue has been fixed in https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/0.3.4 Thanks for submitting this issue report. Closing this issue.
