### ISSUE TITLE
Magento 2.1 Checkout issue with ava tax.

### ISSUE THREAD

**Issue by syedtufail** [classyllama/ClassyLlama_AvaTax#37]
Hi Team

We have installed the ava tax from your git repo, and during system testing we have noticed that we have got issue in checkout page.

The Order Total should reflect the with tax but we are seeing that tax is not considered in total amount however in total deduction at payment gateway the amount is deducted.

Please help us to resolve this issue.

Regards
Tufail Ahmed

**Comment by erikhansen** [comment]
@syedtufail I had another client (using the Magento payment bridge) submit a similar issue. Please review this issue and let me know whether this is the problem you're referring to: https://github.com/classyllama/ClassyLlama_AvaTax/issues/35

**Comment by erikhansen** [comment]
@syedtufail Did you get a chance to review my previous comment?

**Comment by syedtufail** [comment]
Hi erik

We had a look from our side and found that its behaviour is similar to the above problem #35 .
Let us know if magento team has already address this issue or we need to take up this again.


Regards
Tufail Ahmed

**Comment by erikhansen** [comment]
@syedtufail I reached out to the Magento team and this is what they said:

> We identified issues with `window.checkoutConfig.totalsData` object, but after asking Magento 2 core team they confirmed that the object is only used for configuration / display. In other words, is not being updated unless the page is refreshed.
> 
> If you need to get totals from the Javascript  in real time I suggest these approaches:
> * If available, inject the `Magento_Checkout/js/model/quote` and then totals using the method `getTotals`
> * Create an endpoint using the Magento webapi and make an Ajax call (typical approach for Admin pages)
