### ISSUE TITLE
AVATAX calculates tax even for 100% discount on both sub total and shipping amount

### ISSUE THREAD

**Issue by JananiKrishnan** [classyllama/ClassyLlama_AvaTax#39]
Hi,

I have created a cart price rule with $100 off purchase with free shipping. In this rule , if i purchase for less than $100, it will be like 100% discount so the total will $0.00 but the tax is calculating.

I can give you example.

In my order , Subtotal is $20, Shipping is $10 and tax is $2. If I apply the coupon , the grand total should be $0. But the tax amount is calculated as $0.49 and the grand total is $0.49

**Comment by erikhansen** [comment]
@JananiKrishnan What version and edition of Magento are you using? What version of the AvaTax extension are you using (look in composer.json for the version number)?

**Comment by JananiKrishnan** [comment]
Hi erikhansen,
I am using magento CE 2.1.2 and avatax version 0.3.2

**Comment by rameshramachandran84** [comment]
@erikhansen : We are also having the same issue mentioned above . Can you please help us to resolve this issue.

**Comment by rameshramachandran84** [comment]
@erikhansen : Can you please let us know is there any fix implemented for the above issue .

**Comment by JananiKrishnan** [comment]
@erikhansen: Can you please update the fix for this issue?

**Comment by erikhansen** [comment]
@JananiKrishnan @rameshramachandran84 This issue has been fixed in this PR: https://github.com/classyllama/ClassyLlama_AvaTax/pull/43 The fix is in the develop branch. Before we issue this as a new release, can you test this in your environment to ensure it fixes the reported issue?

**Comment by mttjohnson** [comment]
FYI: You can use composer to pull in the develop branch this way:
`composer require classyllama/module-avatax:dev-develop`

**Comment by erikhansen** [comment]
@JananiKrishnan @rameshramachandran84 Have you had a chance to test this yet?

**Comment by erikhansen** [comment]
This issue has been fixed in https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/0.3.4 Thanks for submitting this issue report. Closing this issue.
