### ISSUE TITLE
Error while processing invoice with only free items

### ISSUE THREAD

**Issue by andrelundsett** [classyllama/ClassyLlama_AvaTax#46]
Our franchisees can order some free items from our Magento store. Usually these are shipped and invoiced along with non-free products, and then everything is fine. When, however these items are shipped and invoiced separately with a zero-dollar invoice, the Avatax extension complains. The error “RangeError Summary: Lines is expected to be between 1 and 15000.”, makes good sense, but is problematic since zero-dollar invoices is a valid use case for us. Would it be possible to tweak the extension to handle this gracefully?

See screenshots and excerpt avatax_log.

![image](https://cloud.githubusercontent.com/assets/4931990/21721282/eb459028-d427-11e6-9efc-722390447fa6.png)

![image](https://cloud.githubusercontent.com/assets/4931990/21721355/4462b438-d428-11e6-8dc7-94b48c43a35e.png)

[1.avatax_log.request.and.response.txt](https://github.com/classyllama/ClassyLlama_AvaTax/files/690446/1.avatax_log.request.and.response.txt)

**Comment by erikhansen** [comment]
@andrelundsett I just merged a fix into develop from @mttjohnson that should fix this issue. Can you test and verify the fix?

**Comment by andrelundsett** [comment]
I have tested and confirmed that this fixed our issue. Thank you!

**Comment by erikhansen** [comment]
This issue has been fixed in https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/0.3.4 Thanks for submitting this issue report. Closing this issue.
