### ISSUE TITLE
Uncaught TypeError: require.exec is not a function

### ISSUE THREAD

**Issue by Niranjan2016** [classyllama/ClassyLlama_AvaTax#50]
Hi,
I am facing this error. Following are the details when the error occurs on Magento 2.1.

1. created a custom module page.
2. removed every block from custom module page except content block.
3. In other page wrote a $.get to pull the custom page via ajax.
4. finally trying to add the result received from the $.get call to a div using $("#mydiv").html(result);
5. And $("#mydiv").html(result); statement is where the error is occurring.(although the content gets added but due to error further processing halts)

![screenshot from 2017-01-20 12 43 13](https://cloud.githubusercontent.com/assets/18751159/22139832/b783e4b4-df0e-11e6-913a-a28886208d8f.png)

![screenshot from 2017-01-20 12 42 43](https://cloud.githubusercontent.com/assets/18751159/22139842/cb1a847e-df0e-11e6-8f99-64410f63401e.png)

can you verify pls?
Thanks

**Comment by erikhansen** [comment]
@Niranjan2016 This Github project is for the ClassyLlama_AvaTax extension, not for Magento 2. Did you intend to create this issue on this page? https://github.com/magento/magento2/issues Closing this issue.
