### ISSUE TITLE
Composer Install Failing

### ISSUE THREAD

**Issue by casconed** [classyllama/ClassyLlama_AvaTax#51]
Looks like the dependency for `avalara/avatax` references a repo which has been removed or renamed: https://github.com/avadev/AvaTax-Calc-SOAP-PHP

**Comment by erikhansen** [comment]
@casconed Thanks for notifying us of this issue. I've contacted Avalara and will notify you as soon as I have an update.

**Comment by erikhansen** [comment]
The Github repo is accessible again, so closing this issue. https://github.com/avadev/AvaTax-Calc-SOAP-PHP

Thanks again for reporting this.
