### ISSUE TITLE
Magento EE Gift Card Support

### ISSUE THREAD

**Issue by erikhansen** [classyllama/ClassyLlama_AvaTax#53]
From an AvaTax/Magento 2 merchant:

We are using Magento 2.1.4 Enterprise Edition along with your AvaTax module (classyllama/module-avatax , version 0.3.4). We also use NetSuite with AvaTax. This way, we can estimate the tax on the Magento 2 website for customers, but also are able to place orders directly in NetSuite and have tax calculated correctly. It works ok in most cases, however we have a problem when using Gift Cards (Magento EE default functionality). It looks like when having a gift card, the tax is calculated on 

(Subtotal + Shipping & Handling - Discount) 

While in NetSuite (and the correct way to do it) is: 

(Subtotal + Shipping & Handling – Discount - Gift card discount) 

So the Magento module simply ignores the gift card discount when doing the taxes. The extension’s config options in Magento do not look to provide a setting to include the gift card discount before calculating tax. My guess is that this happens as you calculate tax at row level. While Magento includes the discounts at row level, it never includes the gift card discount, that’s applied directly to the subtotal.

**Comment by erikhansen** [comment]
We did not account for Magento Enterprise's Gift Cards when building this extension, but clearly this is something that we need to address. I have no ETA for resolution, but it is something we would need to address once we address some of the higher priority issues in our backlog.

We _did_ account for Gift Wrapping functionality and I imagine we will need to handle this similarly for gift cards. Screenshot of AvaTax configuration page regarding Gift Wrapping:

![12-39-08 configuration_screenshot png 1508x6752 -zx0le](https://cloud.githubusercontent.com/assets/129031/23624054/f7ac7af0-0269-11e7-8567-588c6608e028.png)

**Comment by erikhansen** [comment]
This has been fixed in release 0.3.5: https://github.com/classyllama/ClassyLlama_AvaTax/releases Closing this issue.

**Comment by rsisco** [comment]
The root of this issue was that AvaTax was charging sales tax on the purchase of a gift card.  According to [this article](https://trustfile.avalara.com/blog/sales-tax-considerations-when-selling-gift-cards/) from Avalara, the sale of a gift card should be tax exempt - which is now the case with the AvaTax extension.
Any purchase made with a gift card is still taxed or not taxed as applicable based on customer, location, items, etc.
