### ISSUE TITLE
Tax is calculated 0 for some addresses

### ISSUE THREAD

**Issue by manaftryzens** [classyllama/ClassyLlama_AvaTax#57]
Hi We have integrated ClassyLlama_AvaTax version 0.3.5 in one of our magento2 projects. The tax calculation is not working for most of the addresses, but it works for a few US based addresses.
We couldn't find any error logs related with this. I have attached the screenshot of certain transactions at Avalara profile as well as the profile settings. 

![profile-settings-2](https://cloud.githubusercontent.com/assets/14325340/24745224/8079d640-1ad2-11e7-8daf-b5aa2bbd8eb7.png)
![profile-settings-1](https://cloud.githubusercontent.com/assets/14325340/24745225/807b93e0-1ad2-11e7-97f2-ce28dfaf390f.png)
![tax-not-calculated](https://cloud.githubusercontent.com/assets/14325340/24745226/807d1b48-1ad2-11e7-9fa5-04759f8c6c3b.png)
![tax-calculated-correctly](https://cloud.githubusercontent.com/assets/14325340/24745227/807ea4c2-1ad2-11e7-9f81-4ca98da70b36.png)

Could you please help us to clear this issue?

**Comment by erikhansen** [comment]
This has been resolved with the release of 1.1.0: https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.1.0
