### ISSUE TITLE
Error when saving configuration with empty credentials

### ISSUE THREAD

**Issue by rsisco** [classyllama/ClassyLlama_AvaTax#60]
When the AvaTax Settings are saved with empty credentials for the selected mode (_Production_ or _Development_), an error message is displayed as shown below:
![image](http://take.ms/OJopa)

**Comment by erikhansen** [comment]
This has been resolved with version [1.0.1 of the extension](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.0.1). This is the error that will now be visible:

![](https://files.classyllama.com/dfcce264/Configuration__Settings__Stores__Magento_Admin_2017-04-18_14-12-25.png)

Closing this issue.
