### ISSUE TITLE
Class AvaTax\ATConfigFactory does not exist

### ISSUE THREAD

**Issue by erikhansen** [classyllama/ClassyLlama_AvaTax#62]
After installing the AvaTax extension using the ["Install by Copying Files"](https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#install-by-copying-files) approach, many merchants have reported getting this error after loading the "STORES > Configuration > SALES > Tax":

```
Class AvaTax\ATConfigFactory does not exist
```

This error typically occurs when a developer tries to manually place the contents of the AvaTax library in `vendor/avalara/avatax`, rather than using Composer to pull in the dependency. A developer *should* use Composer to download the avalara/avatax dependency because files in `vendor` directory only get loaded by PHP if the dependencies were installed via Composer (see the `autoload_*.php` files in the `vendor/composer` directory for context).

**Comment by erikhansen** [comment]
If for whatever reason you're enable to use Composer to install extensions, you may be able to follow these steps to get this module installed. However these are not officially supported and have not been thoroughly tested and you should use them at your own risk. Support will not be provided for merchants using this install method.

For future reference, it looks like this would work for a complete install without the use of composer, and allow the avalara/avatax library to live in the lib/internal directory:

```
wget https://github.com/avadev/AvaTax-Calc-SOAP-PHP/archive/v15.5.1.0.zip -O AvaTax-Calc-SOAP-PHP-15.5.1.0.zip
mkdir -p lib/internal
unzip AvaTax-Calc-SOAP-PHP-15.5.1.0.zip -d lib/internal
mv lib/internal/AvaTax-Calc-SOAP-PHP-15.5.1.0/AvaTax lib/internal/AvaTax
rm -rf lib/internal/AvaTax-Calc-SOAP-PHP-15.5.1.0
rm AvaTax-Calc-SOAP-PHP-15.5.1.0.zip

wget https://github.com/classyllama/ClassyLlama_AvaTax/archive/master.zip -O ClassyLlama_AvaTax-master.zip
mkdir -p app/code/ClassyLlama
unzip ClassyLlama_AvaTax-master.zip -d app/code/ClassyLlama
mv app/code/ClassyLlama/ClassyLlama_AvaTax-master app/code/ClassyLlama/AvaTax
rm ClassyLlama_AvaTax-master.zip
```

The bottom of the app/code/ClassyLlama/AvaTax/registration.php file needs to be updated with this:
```
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::LIBRARY,
    'Avalara_AvaTax',
    BP . DIRECTORY_SEPARATOR . 'lib/internal/AvaTax'
);
```

The `lib/internal` directory is an include path directory set by the Magento autoloader.

As long as the directory name in `lib/internal` matches the namespace of the library which in this case is "AvaTax" PHP will resolve the class name to the files there.

**Comment by githubkadro** [comment]
If you pull the library from github, that file actually does not exist.

**Comment by erikhansen** [comment]
@githubkadro If you are experiencing an issue with this, please open a new issue with full details and steps to reproduce. Thanks!
