### ISSUE TITLE
M2 Avatax Backend add/edit customer address not validating on save

### ISSUE THREAD

**Issue by adpksafety** [classyllama/ClassyLlama_AvaTax#63]
I'm testing the Avatax extension as we're preparing to migrate to Magento 2, and caught an issue with the Avatax address validation. Steps to reproduce:
- Open sales order in admin
- Clicked Edit link beside Shipping Address, and changed the street name to a fake street (I used 123 Fake St.)
- Clicked Save Order Address, and saw happy path confirmation when I expected a validation error message
 
![image](https://cloud.githubusercontent.com/assets/28072876/25461562/7fd58294-2a9e-11e7-94d7-254825e47f4a.png)

**Comment by erikhansen** [comment]
@adpksafety Thanks for submitting this issue. We'll add this task to our backlog. I would not expect resolution on it any time soon as we have several higher priority issues to address first. 

I am aware of the communications you've had with @CNanninga about this issue.

**Comment by adpksafety** [comment]
@erikhansen OK, thank you for adding it to your backlog.

**Comment by erikhansen** [comment]
@adpksafety We have determined that it is highly unlikely that we'll ever add support for this use case as it's a more fringe use case and it's outside the scope of our support agreement with Avalara. We've updated the documentation to explain that this use case is not supported: https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#address_validation_backend_checkout_caveats

Closing this task.
