### ISSUE TITLE
Install doesn't work with table with prefix

### ISSUE THREAD

**Issue by jeremybouvet** [classyllama/ClassyLlama_AvaTax#67]
Hi !

When installing the module on a Magento 2 which uses prefix on table name, we get the following error : 
Base table or view not found: 1146 Table 'xxx.sales_invoice' doesn't exist, query was: DESCRIBE `sales_invoice`

The issue comes in the file /Setup/UpgradeData.php, L35 / L37.
The function tableColumnExists first parameter must have the prefix already.

Instead of : 
`// Only copy data and drop columns from "sales_invoice" if the columns exist

            if (
                $setup->getConnection(self::$connectionName)
                    ->tableColumnExists('sales_invoice', 'avatax_is_unbalanced')
                && $setup->getConnection(self::$connectionName)
                    ->tableColumnExists('sales_invoice', 'base_avatax_tax_amount')
            )
`
We should have : 
`// Only copy data and drop columns from "sales_invoice" if the columns exist

            if (
                $tableName = $this->getTable('sales_invoice');

                $setup->getConnection(self::$connectionName)
                    ->tableColumnExists($tableName, 'avatax_is_unbalanced')
                && $setup->getConnection(self::$connectionName)
                    ->tableColumnExists($tableName, 'base_avatax_tax_amount')
            )
`

Thanks !

**Comment by erikhansen** [comment]
@jeremybouvet Thanks for submitting this issue. If you're interested in submitting a PR to fix this issue, we'd gladly accept it and include it in our next release. If not, we'll add this to our backlog and get it addressed as soon as possible.

**Comment by jeremybouvet** [comment]
Hi !

I've created the pull request, hopefully, I did it the right way.
https://github.com/classyllama/ClassyLlama_AvaTax/pull/69

Thanks,

**Comment by rsisco** [comment]
@jeremybouvet - Thank you. We'll review the PR, make any necessary changes, and get it merged in.

**Comment by erikhansen** [comment]
This issue has been resolved with release [1.1.2](https://github.com/classyllama/ClassyLlama_AvaTax/releases) of this extension. Thanks for reporting!
