### ISSUE TITLE
Extension ignores mode setting set in store view

### ISSUE THREAD

**Issue by rsisco** [classyllama/ClassyLlama_AvaTax#68]
Although the setting is available, the mode setting at the store view level is ignored and the default config setting is used in every case.
![image](http://take.ms/X5upe)

**Comment by erikhansen** [comment]
This has been fixed in version [1.1.1](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.1.1) of this extension via PR #71.
