### ISSUE TITLE
Add module to https://packagist.org/

### ISSUE THREAD

**Issue by pivulic** [classyllama/ClassyLlama_AvaTax#8]
Hello,

Could you please add the module to https://packagist.org/ so it can be installed from there, similar to i.e. https://packagist.org/packages/adyen/module-payment and https://packagist.org/packages/magestore/module-bannerslider?

See https://packagist.org/search/?q=avatax how other vendors are doing, these would really help us!

**Comment by erikhansen** [comment]
@pivulic I've added this extension to Packagist: https://packagist.org/packages/classyllama/module-avatax

**Comment by pivulic** [comment]
:+1:
