### ISSUE TITLE
Avatax Module Update Issue in Magento 2.1.2 EE

### ISSUE THREAD

**Issue by ezestrajesh** [classyllama/ClassyLlama_AvaTax#83]
I have upgraded Avatax module to latest version ( 1.1.4 ) in Magento 2.1.2 EE and we are facing below issue while running cron

( php bin/magento cron:run )command on CLI
/usr/bin/php /usr/share/nginx/html/magento/bin/magento cron:runPHP Fatal error: Uncaught Error: Call to a member function getId() on null in /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Helper/TaxClass.php:241Stack trace:#0 /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Framework/Interaction/Tax.php(607): ClassyLlama\AvaTax\Helper\TaxClass->populateCorrectTaxClasses(Array, '1')#1 /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Framework/Interaction/Tax/Get.php(123): ClassyLlama\AvaTax\Framework\Interaction\Tax->getGetTaxRequestForSalesObject(Object(Magento\Sales\Model\Order\Invoice\Interceptor))#2 /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Model/Queue/Processing.php(350): ClassyLlama\AvaTax\Framework\Interaction\Tax\Get->processSalesObject(Object(Magento\Sales\Model\Order\Invoice\Interceptor))#3 /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Model/Queue/Processing.php(183): ClassyLlama\AvaTax\Model\Queue\Processing->processWithAvaTax(Object(ClassyLlama\AvaTax\Model\Queue), Object(Magento\Sales\Model in /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Helper/TaxClass.php on line 241Fatal error: Uncaught Error: Call to a member function getId() on null in /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Helper/TaxClass.php:241Stack trace:#0 /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Framework/Interaction/Tax.php(607): ClassyLlama\AvaTax\Helper\TaxClass->populateCorrectTaxClasses(Array, '1')#1 /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Framework/Interaction/Tax/Get.php(123): ClassyLlama\AvaTax\Framework\Interaction\Tax->getGetTaxRequestForSalesObject(Object(Magento\Sales\Model\Order\Invoice\Interceptor))#2 /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Model/Queue/Processing.php(350): ClassyLlama\AvaTax\Framework\Interaction\Tax\Get->processSalesObject(Object(Magento\Sales\Model\Order\Invoice\Interceptor))#3 /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Model/Queue/Processing.php(183): ClassyLlama\AvaTax\Model\Queue\Processing->processWithAvaTax(Object(ClassyLlama\AvaTax\Model\Queue), Object(Magento\Sales\Model in /usr/share/nginx/html/magento/vendor/classyllama/module-avatax/Helper/TaxClass.php on line 241
Please help us to resolve the issue.

Regards,
Rajesh

**Comment by rsisco** [comment]
@ezestrajesh - Is this issue reproducible in a native Magento installation with sample data? If not, please contact us at AvaTaxSupport@ClassyLlama.com so we may talk specifics about your environment and determine whether a bug exists.

**Comment by rsisco** [comment]
Closing issue due to no response.
