### ISSUE TITLE
Magento 2.2.0 Compatibility

### ISSUE THREAD

**Issue by loganstellway** [classyllama/ClassyLlama_AvaTax#85]
The most recent release of Magento 2 is [version 2.2.0](http://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html). The ClassyLlama AvaTax module has a defined dependency on `magento/framework:^100.1.0`, however Magento 2.2.0 requires `magento/framework:101.0.0`. 

This dependency definition prevents upgrading a Magento 2 instance to the latest version.

**Comment by erikhansen** [comment]
@loganstellway - See below. Please let us know the results of your testing, if you choose to proceed with installing this on 2.2.

@rsisco - As you know, we have an internal task to test compatibility with Magento 2.2. However until that's done, I think we should allow merchants to upgrade to 2.2.0 at their own risk. Can you:

1. Edit the https://github.com/classyllama/ClassyLlama_AvaTax/blob/develop/composer.json file to allow the extension to be installed 2.1.x and 2.2.x. You may want to reference https://getcomposer.org/doc/articles/versions.md for how to best do this.
2. Update the module's readme (https://github.com/classyllama/ClassyLlama_AvaTax#magento-version-support) to explicitly state that Magento 2.2.x has not been tested yet.

**Comment by franckgarnier21** [comment]
Any update or workaround for this Magento 2.2 upgrade ?

**Comment by loganstellway** [comment]
@franckgarnier21 
I have created a [pull request](https://github.com/classyllama/ClassyLlama_AvaTax/pull/86) for the changes asked for by @erikhansen above.

@erikhansen / @rsisco 
Can you please merge the changes or create a branch specifically for this issue? 

Thanks!

**Comment by erikhansen** [comment]
@rsisco Can you regard @loganstellway's comment today?

**Comment by rsisco** [comment]
@loganstellway - I've merged your PR (with a slight change to the ReadMe) into the `develop` branch.

To change your AvaTax installation to track with the develop branch, you should run:
````
composer require classyllama/module-avatax:dev-develop
````

**Comment by franckgarnier21** [comment]
Many thanks for your quick update

**Comment by loganstellway** [comment]
@rsisco 
Thank you! I will be implementing this on a test environment in the near future. I will report back with any issues.

**Comment by erikhansen** [comment]
@loganstellway How has your testing with 2.2 gone? Have you discovered any issues? We're going to start our 2.2 testing next week.

**Comment by JosephMaxwell** [comment]
@erikhansen: any update on when the 2.2 compatibility will be finalized?

**Comment by erikhansen** [comment]
@JosephMaxwell We finished testing today and uncovered a few minor issues. We'll be working on resolution of those issues over the coming week and I hope we'll have it released by the end of next week.

**Comment by JosephMaxwell** [comment]
@erikhansen: thank you.

**Comment by rsisco** [comment]
This is has been resolved as of [release 1.2.3](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.2.3). Closing issue.

**Comment by rsisco** [comment]
We've just identified a bug in release 1.2.3 that prevents DI compilation. We are quickly addressing the issue and will release a new version shortly with a fix.

**Comment by rsisco** [comment]
A [new release](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.2.4) has been published fixing the DI compilation issue. Closing issue.

**Comment by almsmack** [comment]
Have you had a chance to make progress on this testing? Any projected timeframe for official Magento 2.2 compatibility?

**Comment by erikhansen** [comment]
@almsmack The latest version of this extension supports 2.2.0. However that version has not yet made it on to the Marketplace, so you'll need to install it using one of the methods documented here: https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#installation
