### ISSUE TITLE
[Question] Creditmemo support

### ISSUE THREAD

**Issue by franckgarnier21** [classyllama/ClassyLlama_AvaTax#87]
Hello,

It is not an issue, but I want to have more information on how Creditmemos are managed with Avatax module.

Can you explain me if you support both Full Credimemo and Partial Creditmemo and how can I retrieve the different taxes for the partial creditmemo ?
Does the taxes are calculated based on the order purchased date or creditmemo date ? (past date)

You can only give me the class reference if it is easier for you.

Many thanks,

**Comment by rsisco** [comment]
@franckgarnier21 -
Credit memos can be issued either for an entire invoice or just specific items on the invoice and sales tax is calculated only on items being refunded.

When a credit memo is issued, AvaTax will supply the original invoice date for tax calculation. You can see this in the screenshot below of the API response for a credit memo issued on 10/18/17 for an invoice created on 9/26/17:
![img](http://take.ms/1sh2M)

And you can find this in the code in the following method: `\ClassyLlama\AvaTax\Framework\Interaction\Tax::getGetTaxRequestForSalesObject`

**Comment by franckgarnier21** [comment]
Hello,

If I understand correctly, the request for invoice and creditmemo are performed only if we set Tax mode to 'Estimate Tax & Submit Transactions to AvaTax'. What is the impact for the customer to submit transactions to Avatax ?

Then you process invoice and creditmemo (asynch). But you retrieve and store only the total tax amount.

My customer needs to show to their customer the tax details for invoice and creditmemo (partial and full). In their invoice / creditmemo PDF on Magento.

But the tax details is only retrieved during quote estimation and stored in sales_order_tax table.

How can I achieve to retrieve the tax applied details for invoice and creditmemo (partial and full).

This is a sample response for a creditmemo :

`
    AvaTax\GetTaxResult Object
(
    [DocCode:AvaTax\GetTaxResult:private] => 21000000003123-79683485655
    [DocId:AvaTax\GetTaxResult:private] => 3020099622
    [AdjustmentDescription:AvaTax\GetTaxResult:private] => 
    [DocDate:AvaTax\GetTaxResult:private] => 2017-12-12
    [TaxDate:AvaTax\GetTaxResult:private] => 2017-12-12
    [DocType:AvaTax\GetTaxResult:private] => ReturnInvoice
    [DocStatus:AvaTax\GetTaxResult:private] => Committed
    [Reconciled:AvaTax\GetTaxResult:private] => 
    [Locked:AvaTax\GetTaxResult:private] => 
    [Timestamp:AvaTax\GetTaxResult:private] => 2017-12-12T10:25:03.677
    [TotalAmount:AvaTax\GetTaxResult:private] => -16700
    [TotalDiscount:AvaTax\GetTaxResult:private] => 0
    [TotalExemption:AvaTax\GetTaxResult:private] => 0
    [TotalTaxable:AvaTax\GetTaxResult:private] => -16700
    [TotalTax:AvaTax\GetTaxResult:private] => -1027
    [AdjustmentReason:AvaTax\GetTaxResult:private] => 0
    [Version:AvaTax\GetTaxResult:private] => 1
    [TaxLines:AvaTax\GetTaxResult:private] => stdClass Object
        (
        )
    [TotalTaxCalculated:AvaTax\GetTaxResult:private] => -1027
    [TaxSummary:AvaTax\GetTaxResult:private] => stdClass Object
        (
        )
    [TransactionId:AvaTax\GetTaxResult:private] => 5347383036919228
    [ResultCode:AvaTax\GetTaxResult:private] => Success
    [Messages:AvaTax\GetTaxResult:private] => Array
        (
        )
    [HashCode] => 0
    [TaxAddresses] => stdClass Object
        (
        )
    [VolatileTaxRates] => 1
)
`

`MariaDB [straps-test]> select * from avatax_sales_creditmemo;
+-----------+-----------+---------------+------------------------+
| entity_id | parent_id | is_unbalanced | base_avatax_tax_amount |
+-----------+-----------+---------------+------------------------+
|         1 |       818 |             0 |              1027.0000 |
+-----------+-----------+---------------+------------------------+`


Should I only update the DetailLevel of your request.

Can you guide me how to customize your code, or say me if this feature is plan on your roadmap ?

Many thanks.
