### ISSUE TITLE
Address Validation is breaking customAttribute data

### ISSUE THREAD

**Issue by Silarn** [classyllama/ClassyLlama_AvaTax#88]
Magento normally does not have customAttribute data in addresses, but it is supported. One of our modules uses this to support custom customer and order attributes. However, with the address validation enabled this data is being rewritten from:

custom_attribute: {
attribute_name: "value"
}

to

custom_attribute: {
entity: "attribute_name",
value: "value"
}

which does not validate and breaks checkout (and possibly other address forms).

**Comment by erikhansen** [comment]
@Silarn Can you provide us a copy of the extension with detailed instructions on how to reproduce this issue? You can email me at `<my first name>@classyllama.com`.

**Comment by erikhansen** [comment]
@Silarn I'm going to close this task until you're able to provide detailed steps to reproduce. Once you post those details, I'll re-open this task.

**Comment by Silarn** [comment]
I can't provide the module, but I can give more insight into the issue.

So it seems that once 'custom_attributes' is saved into the address model, the data gets converted to the above format. Because you are reading this data and passing it back in the payments extension data, we get it back in the converted format. This usually isn't an issue because we don't usually get address data back from the server during checkout unless it's being populated in a form which will resubmit it based on the form names. However, because you're setting it directly it ends up in the incorrect format.

I think the only solution is to convert the custom_attributes data back to the correct frontend format when submitting the data to the JS checkout quote.

The view/frontend/web/js/view/update-address.js is where this address data is set back onto the quote model in checkout.

https://github.com/classyllama/ClassyLlama_AvaTax/blob/4eb7c9336c100091c24413379181e25e58f2bc79/view/frontend/web/js/view/update-address.js#L31

Here we have a jQuery.each function that takes the API data and converts it to the JS array format used by the checkout scripts. Essentially, you need a check in there that looks for 'custom_attributes' and converts it from the 

```JavaScript
custom_attributes: [
{"entity": "attribute_name",
"value": "value"},
{"entity": "second_attribute",
"value": "another value"}
]
```

form to the 

```JavaScript
custom_attributes: {
"attribute_name": "value",
"second_attribute": "another value"
}
```

form.

**Comment by Silarn** [comment]
Alternatively you can just drop the custom_attributes data which should merge with the original address data and preserve the original format.

Trying to submit in the altered format will cause a validation error which interrupts the submission.

**Comment by erikhansen** [comment]
@Silarn Thanks for providing the additional detail. I've added this to our backlog of issues, but it will be at least a few months before we're able to do anything with this. We would be happy to accept a PR that fixes this issue.
