### ISSUE TITLE
Issue with extension attributes in plugin/interceptor

### ISSUE THREAD

**Issue by KevinMace** [classyllama/ClassyLlama_AvaTax#93]
### Preconditions
1. Magento EE 2.1.7
2. avalara/avatax 15.5.2
3. PHP 7.0.8

### Steps to reproduce
1. Attempted to add an item to the cart on a product page

### Expected result
1.  Server returns 200 and adds item to the cart

### Actual result
1. Server returns a 500 error, item not added to the cart.

The following error is logged in the apache logs

``
 Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getTax() on null in /path/to/magento/vendor/classyllama/module-avatax/Plugin/Sales/Total/Quote/CommonTaxCollector.php:43
``

Which relates to this line of code, the 'getExtensionAttributes' is returning NULL instead of an object.

``
'extension_attributes' => ['tax' => $rateDataObject->getExtensionAttributes()->getTax()]
``

**Comment by rsisco** [comment]
@KevinMace - are you still able to reproduce the issue after clearing the Magento cache and performing a DI compile:
`bin/magento cache:flush`
`bin/magento setup:di:compile`

Are you able to reproduce the issue on a vanilla Magento 2 install using the latest version of the AvaTax extension? If you can reproduce the issue, please provide specific steps for doing so.

**Comment by KevinMace** [comment]
@rsisco Yes, even after clearing the cache, deleting var/generation, var/cache and running the di:compile command the issue was still occurring.

The AvaTax version is the one set in this extensions dependency list in the composer.json, which does appear to be their latest release https://github.com/avadev/AvaTax-Calc-SOAP-PHP/releases

I'll try with a vanilla Magento 2 install and see how that goes.

**Comment by KevinMace** [comment]
@rsisco I've been doing some testing using a vanilla Magento EE 2.1.10 install, I can confirm that issue does still occur. These are the steps I went through to recreate the issue.

1. Within Stores -> Configuration -> General -> Country Options, set the default country to 'United Kindom'

<img width="538" alt="screen shot 2017-11-30 at 21 58 48" src="https://user-images.githubusercontent.com/1065240/33457206-ac4ab94e-d619-11e7-9635-af1305e33e66.png">


2. Within Stores -> Configuration -> Sales -> Tax, set the following within the 'Default Tax Destination Calculation' section

<img width="975" alt="screen shot 2017-11-30 at 21 57 33" src="https://user-images.githubusercontent.com/1065240/33457183-968abb4a-d619-11e7-910e-895e48397a39.png">


3. Setup the following tax rate/zone within Stores -> Tax Zones and Rates

<img width="1045" alt="screen shot 2017-11-30 at 22 00 31" src="https://user-images.githubusercontent.com/1065240/33457280-eb0dad8a-d619-11e7-9ec3-70dbb9836a2c.png">

4. Setup the following Tax Rule within Stores -> Tax Rules, using the rate/zone we just setup

<img width="1012" alt="screen shot 2017-11-30 at 22 01 52" src="https://user-images.githubusercontent.com/1065240/33457351-1d051efe-d61a-11e7-8f58-1a162e0992b4.png">

5. Create a product that uses the Tax Class = "Taxable Goods"

6. Go to a product page and attempt to add the product to the cart, you should see the following error.

<img width="837" alt="screen shot 2017-11-30 at 22 04 49" src="https://user-images.githubusercontent.com/1065240/33457509-960a1f3e-d61a-11e7-8912-ddc85158a2e2.png">

``
[Thu Nov 30 21:51:25.993642 2017] [proxy_fcgi:error] [pid 8594] [client 127.0.0.1:46972] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getTax() on null in /mnt/project/vendor/classyllama/module-avatax/Plugin/Sales/Total/Quote/CommonTaxCollector.php:43
``

**Comment by rsisco** [comment]
@KevinMace - Thank you for the update, I am working on reproducing locally and providing a resolution.

**Comment by rsisco** [comment]
@KevinMace - We've released a [new version](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.2.6) of the extension that addresses this issue. Please update the extension and reopen this issue if needed.
Closing issue.

**Comment by KevinMace** [comment]
@rsisco Great, thank you. I'll install the new version today and see how we get on.
