### ISSUE TITLE
Excpetion during order submission

### ISSUE THREAD

**Issue by monikanemade** [classyllama/ClassyLlama_AvaTax#98]
### Preconditions
We are using ClassyLlama_AvaTax module 1.0.2 in our project with Magetno 2.1.9.

On production server, we are getting below error for some orders. We were receiving this error with Magento 2.1.7 as well. Please let us know if there is any fix available for it.

Error Trace:
Error: Uncaught exception 'Error' with message 'Call to a member function getId() on null' in /app/code/ClassyLlama/AvaTax/Helper/TaxClass.php:241
in ClassyLlama\AvaTax\Helper\TaxClass::populateCorrectTaxClasses called at /app/code/ClassyLlama/AvaTax/Framework/Interaction/Tax.php (601) in ClassyLlama\AvaTax\Framework\Interaction\Tax::getGetTaxRequestForSalesObject called at /app/code/ClassyLlama/AvaTax/Framework/Interaction/Tax/Get.php (123) in ClassyLlama\AvaTax\Framework\Interaction\Tax\Get::processSalesObject called at /app/code/ClassyLlama/AvaTax/Model/Queue/Processing.php (350) in ClassyLlama\AvaTax\Model\Queue\Processing::processWithAvaTax called at /app/code/ClassyLlama/AvaTax/Model/Queue/Processing.php (183) in ClassyLlama\AvaTax\Model\Queue\Processing::execute called at /app/code/ClassyLlama/AvaTax/Model/Queue.php (139) in ClassyLlama\AvaTax\Model\Queue::process called at /app/code/ClassyLlama/AvaTax/Model/Queue/Task.php (164) in ClassyLlama\AvaTax\Model\Queue\Task::processPendingQueue called at /app/code/ClassyLlama/AvaTax/Model/Queue/Task.php (143) in ClassyLlama\AvaTax\Model\Queue\Task::cronProcessQueue called at ? (?) in call_user_func_array called at /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php (247) in Magento\Cron\Observer\ProcessCronQueueObserver::_runJob called at /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php (195) in Magento\Cron\Observer\ProcessCronQueueObserver::execute called at /vendor/magento/framework/Event/Invoker/InvokerDefault.php (73) in Magento\Framework\Event\Invoker\InvokerDefault::_callObserverMethod called at /vendor/magento/framework/Event/Invoker/InvokerDefault.php (61) in Magento\Framework\Event\Invoker\InvokerDefault::dispatch called at /vendor/magento/module-staging/Model/Event/Manager.php (97) in Magento\Staging\Model\Event\Manager::dispatch called at /var/generation/Magento/Staging/Model/Event/Manager/Proxy.php (95) in Magento\Staging\Model\Event\Manager\Proxy::dispatch called at /vendor/magento/framework/App/Cron.php (74) in Magento\Framework\App\Cron::launch called at /vendor/magento/module-cron/Console/Command/CronCommand.php (98) in Magento\Cron\Console\Command\CronCommand::execute called at /vendor/symfony/console/Symfony/Component/Console/Command/Command.php (257) in Symfony\Component\Console\Command\Command::run called at /vendor/symfony/console/Symfony/Component/Console/Application.php (874) in Symfony\Component\Console\Application::doRunCommand called at /vendor/symfony/console/Symfony/Component/Console/Application.php (195) in Symfony\Component\Console\Application::doRun called at /vendor/magento/framework/Console/Cli.php (96) in Magento\Framework\Console\Cli::doRun called at /vendor/symfony/console/Symfony/Component/Console/Application.php (126) in Symfony\Component\Console\Application::run called at /bin/magento (23)

**Comment by rsisco** [comment]
Closing this issue as it has been resolved since release 1.2.5.
