### ISSUE TITLE
Need to configure Customer Code Format using another attribute

### ISSUE THREAD

**Issue by JesKingDev** [classyllama/ClassyLlama_AvaTax#99]
### Preconditions
1. Magento 2.2 Open Source
2. Avatax module 1.2.6
3. PHP 7.1.8
4. MySQL 5.6.35

### Steps to reproduce
1. In Avatax configuration, locate Data Mapping Section.
2. Locate Customer Code Format dropdown.
3. Attempt to select a custom attribute used to map the customer number in Avalara.

### Expected result
1. Expect to provide text based entry or select from dropdown of all customer attributes (ex. field called ext_customer_number, erp_customer_number, avalara_customer_number, etc.)

### Actual result
1. Only options are ID, Email, Name (ID)

**Comment by rsisco** [comment]
@JesKingDev - I am working on adding this enhancement to the next version of the extension.

**Comment by JesKingDev** [comment]
Awesome thanks! Any ETA on availability?

**Comment by rsisco** [comment]
@JesKingDev - I hope to release a new version by the end of next week.

**Comment by rsisco** [comment]
@JesKingDev - This has been added to the latest release ([1.3.0](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.3.0)); which I have just published.

Closing this issue.

**Comment by JesKingDev** [comment]
@rsisco This enhancement works if the is_user_defined field = 1, however there are other scenarios where the value needs to be defined by administrators, or by 3rd party extensions, and is_user_defined needs to be 0. Can you refine this functionality to allow for this scenario as well?

**Comment by JesKingDev** [comment]
@rsisco Any ETA on a fix for this issue?

**Comment by rsisco** [comment]
@JesKingDev - I just published [release 1.4.0](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.4.0) to include the ability to use _any_ customer attribute for the Customer Code.

**Comment by JesKingDev** [comment]
Thanks, @rsisco !

**Comment by rsisco** [comment]
@JesKingDev - Wow, this is the issue that just won't die. I just published a [new release](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.4.1) that addresses this problem.
